### ISSUE TITLE
AttributeError: 'tqdm_notebook' object has no attribute 'reset'

### ISSUE THREAD

**Issue by mmsamiei** [PyTorchLightning/pytorch-lightning#1013]
## 🐛 Tqdm Bug

torch                    1.4.0
tqdm                     4.43.0
pytorch-lightning        0.6.1

```
AttributeError                            Traceback (most recent call last)

<ipython-input-15-58842400eb19> in <module>()
      5 # most basic trainer, uses good defaults
      6 trainer = Trainer(min_epochs=4, max_epochs=4, train_percent_check=0.001, val_percent_check=0.001, accumulate_grad_batches=8, gpus=[0])
----> 7 trainer.fit(model)

3 frames

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    375                 # .reset() doesn't work on disabled progress bar so we should check
    376                 if not self.main_progress_bar.disable:
--> 377                     self.main_progress_bar.reset(num_iterations)
    378                 desc = f'Epoch {epoch + 1}' if not self.is_infinite_dataloader(self.train_dataloader) else ''
    379                 self.main_progress_bar.set_description(desc)

AttributeError: 'tqdm_notebook' object has no attribute 'reset'
```

**Comment by wassname** [comment]
It works for me without crashing, [see this notebook](https://gist.github.com/wassname/abec057ebde114c252fd9804e141e10b). Perhaps post a self contained working example of the problem?

pytorch-lightning-0.6.0
tqdm==4.41.1
torch==1.3.0+cu92
Python 3.7.3

**Comment by acarrera94** [comment]
I had this same issue when running on google Colab. the solution is that when you run `!pip install git+git://github.com/williamFalcon/pytorch-lightning.git@master --upgrade` at the end of the output from the cell it will say: 

> The following packages were previously imported in this runtime:
  [tqdm] You must restart the runtime in order to use newly installed versions.

And there's `RESTART RUNTIME` button below. Just click on that and continue with your next cells!
