### ISSUE TITLE
Update `core/lightning.py` to `core/lightning_module.py`

### ISSUE THREAD

**Issue by rohitgr7** [PyTorchLightning/pytorch-lightning#10499]
## Proposed refactoring or deprecation

Update `core/lightning.py` to `core/lightning_module.py`
Possibly also update `core/datamodule.py` to `core/lightning_datamodule.py`

### Motivation

Update it since `core/lightning.py` only contains `LightningModule` so the filename doesn't signify what it contains.

### Pitch

It's a simple update. We can deprecate the old filename. Need approvals if it looks good.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @carmocca @borda @ananthsub @ninginthecloud @jjenniferdai

**Comment by tchaton** [comment]
Hey @rohitgr7,

I am in favour of this. It would make discoverability of the code simpler.

@ananthsub @awaelchli @carmocca Any thoughts ?

**Comment by carmocca** [comment]
Agree with the renaming.

However, it should be `core/lightning.py` to `core/module.py`

because if we choose `core/lighting_module.py`, the following should also be changed
`core/datamodule.py` -> `core/data_module.py` (already pointed out in the top post)
`lite/lite.py` -> `lite/lightning_lite.py`
`utilities/cli.py` -> `utilities/lightning_cli.py`

**Comment by Borda** [comment]
> Agree with the renaming.

I would say that the `lite/lite.py` is not very good as well as `trainer/trainer.py`

> thoughts?

I agree with the name, just has `module.py` only ay be confusing as the same name is in PT, so could be included somehow that this module is for models or its base? aka core/lightning.py -> core/base_module.py

**Comment by carmocca** [comment]
> I agree with the name, just has module.py only ay be confusing as the same name is in PT, so could be included somehow that this module is for models or its base? aka core/lightning.py -> core/base_module.py

But that's a separate topic, which would be if `LightningModule` is a good name.
It should only be `base_module` if `LightningModule` was renamed to `BaseModule`.

This issue is just about consistency of the filenames. The current format is `class LightningX` -> `X.py`

So either (1):
- `lightning.py` is adapted to `module.py` for consistency with the format
- the format is changed to `class LightningX` -> `lightning_X.py`

**Comment by tanmoyio** [comment]
@rohitgr7 I want to work on it,

**Comment by akihironitta** [comment]
Hi @tanmoyio! That'll be great! Assigned this issue to you :)

**Comment by tanmoyio** [comment]
@akihironitta so `core/lightning.py` -> `core/modules.py` ?
won't it affect the tests ?
