### ISSUE TITLE
Move cuda related benchmark code from accelerator connector to GPU accelerator

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#10536]
## Proposed refactoring or deprecation

Move this line of code to GPU accelerator
https://github.com/PyTorchLightning/pytorch-lightning/blob/7a9a08c5d3ca4699fb439f691c40e1320b37507a/pytorch_lightning/trainer/connectors/accelerator_connector.py#L183-L184

Alternatively, can we deprecate the `benchmark` flag as mentioned by @justusschock in #9006?

### Motivation

Since this line of code is specific to GPU accelerator, it should live in that class, not in the generic accelerator_connector.

**Comment by tchaton** [comment]
Yes, this makes sense.

**Comment by kaushikb11** [comment]
@tchaton I don't think it does.

@daniellepintz How do you think would be the best way to pass `benchmark` to the GPUAccelerator without breaking the current interface?

**Comment by daniellepintz** [comment]
@kaushikb11 Hmm, what about putting `torch.backends.cudnn.benchmark = trainer.benchmark` in this method:
https://github.com/PyTorchLightning/pytorch-lightning/blob/247f5aacc2fc96ab1df14d7176838dc65757a786/pytorch_lightning/accelerators/gpu.py#L44-L46

**Comment by kaushikb11** [comment]
@daniellepintz Sounds good! Let's do it.

**Comment by awaelchli** [comment]
Should we consider making it a constructor argument to the GPU Accelerator? 
+ no trainer reference needed
+ gets set as early as possible (as early as when the connector instantiates the accelerator)

**Comment by ananthsub** [comment]
I think the initial proposal adds more complexity across components than is needed right now. 

To set a single torch flag (w/ no side-effects or errors if cudnn isn't used), Lightning would now:
- initialize a property on the Trainer (already present)
- Look up the property from another class (GPU accelerator)
- Set the flag there

This makes it harder to follow what the flag does (one needs to hop from Trainer -> accelerator connector -> GPU accelerator).

What I am more wary of is, if in the future, `benchmark` expands to cover more backends, the same way `determinstic` did. Before, the implementation for `deterministic` was to set `torch.backends.cudnn.deterministic`. Later, PyTorch offered a generic `torch.use_deterministic_algorithms`. If we had made `deterministic` part of the GPU accelerator interface, we'd have to unwind that, by either making `deterministic` part of every accelerator/strategy, or factoring the flag out from all of them and setting it directly in the Trainer, as is done now. 

Since `torch.backends.cudnn.benchmark` can be done right now without errors for hardware, I'm fine with leaving the code as is.

**Comment by awaelchli** [comment]
Are there any signs that  torch.backends.cudnn.benchmark will disappear? I would argue as long as the name "cudnn" is included there, it fits perfectly into the GPU accelerator, especially because we will have the facility to properly teardown this setting. I imagine this:

```py
class GPUAccelerator(Accelerator):
    def __init__(self, benchmark=False):
        self._benchmark = benchmark

    setup(self):
        ...
        torch.backends.cudnn.benchmark = self._benchmark

    def teardown(self):
        ...
        torch.backends.cudnn.benchmark = False
```

**Comment by daniellepintz** [comment]
I agree with @awaelchli, I think it fits perfectly into the GPU accelerator and doesn't really have a place in the accelerator_connector, where it is now.

Currently we are setting `torch.backens.cudnn.benchmark` all the time, even when we aren't using GPUs, which doesn't make sense:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9826de21625b162dfef43f30864b5a6d9efab003/pytorch_lightning/trainer/connectors/accelerator_connector.py#L183

**Comment by ananthsub** [comment]
> Are there any signs that torch.backends.cudnn.benchmark will disappear?

No, there are no such signs.

I think the constructor approach addresses the complexity concern, which LGTM

**Comment by daniellepintz** [comment]
After thinking more about this, I think @ananthsub is right, and making this change adds more complexity than it's worth. I suggest we close this issue
