### ISSUE TITLE
Lite doesn't seem to work with the registry.

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#10616]
### To Reproduce

```py
Lite(strategy="deepspeed_zero_3")
```

### Environment

- PyTorch Lightning Version (e.g., 1.3.0):
- PyTorch Version (e.g., 1.8)
- Python version:
- OS (e.g., Linux):
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information:

### Additional context

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
Yes, that's intentional. The misconfiguration error you should see is printed here in Lite: 
https://github.com/PyTorchLightning/pytorch-lightning/blob/2c7c4aab8087d4c1c99c57c7acc66ef9a8e815d4/pytorch_lightning/lite/lite.py#L462-L469


We don't support it right now and afaik the docs don't mention any support for this.
We could probably add it, but I would be careful here since we don' t support all accelerators and strategies in Lite yet. 

Note: typo in your string "deepspeed_zero_3", should be "deepspeed_stage_3"

**Comment by tchaton** [comment]
Closing this issue as it was intentional.
