### ISSUE TITLE
[RFC] simplify X_step_context() function in precision_plugin()

### ISSUE THREAD

**Issue by four4fish** [PyTorchLightning/pytorch-lightning#10891]
## Proposed refactor

Merge train_step_context, val_step_context, test_step_context, predict_step_context to step_context() as they all have same logic and no overrides from subclasses. 

### Motivation

Remove duplicated code and simplification

### Pitch
Merge these code to one
https://github.com/PyTorchLightning/pytorch-lightning/blob/038c151b6ee0754adb66714a62bf32b0a389511f/pytorch_lightning/plugins/precision/precision_plugin.py#L218-L240

### Additional context

Related to #10648, but not a blocker

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @kaushikb11 @ananthsub

**Comment by awaelchli** [comment]
Yes the code is duplicated, but to be clear, this was intentional. These hooks were meant to give custom implementations the flexibility to provide different context managers per `*_step` category. 

Now granted, we haven't seen any use of this. The motivation for this ticket should imo probably be along the lines of: We want to take a step back and converge to a minimal interface that is maintanable, but be open for it to expand again should such requirements come up in the future.

If we decide to remove them, I would go with the `forward_context()` that's already there as the one that we use. The naming would be in line with both Lite and Lightning.

**Comment by justusschock** [comment]
I also think that we may want to differentiate between a forward and a backward context and other then that they should be same for all stages (ofc the backward one won't be used for validation).

I also remember that we have some backward things in a context somewhere (I think in precision)

**Comment by tchaton** [comment]
Hey @four4fish,

This is something we haven't explored yet, but it would enable users to implement custom precision scheduling strategies with minimal effort.

I believe this is worth keeping.
