### ISSUE TITLE
🛠 Refactor setup.py to setup.cfg

### ISSUE THREAD

**Issue by k4black** [PyTorchLightning/pytorch-lightning#10981]
## Proposed refactor

Use `setup.cfg` for static metadata

### Motivation

According to [packaging.python.org/en/latest/tutorials/packaging-projects/](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
> Static metadata (setup.cfg) should be preferred

Because is:
> guaranteed to be the same every time. This is simpler, easier to read, and avoids many common errors, like encoding errors.

### Pitch

Perform a small refactor of `setup.py` file to move max of the static metadata to `setup.cfg`

### Additional context

Pre-request changes can be found at [github.com/k4black/pytorch-lightning/blob/setup-fix/setup.cfg](https://github.com/k4black/pytorch-lightning/blob/setup-fix/setup.cfg)

cc @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
@Borda @carmocca can/should this be done?

**Comment by k4black** [comment]
Note: Similarly, I'm not sure that there is a separate `setup_tools.py` included in the pkg. It can be moved directly in the refactored `setup.py`

**Comment by Borda** [comment]
I am fine with moving all static attributes to `setup.cfg`
just be aware the `attr: pytorch_lightning.__about__.__version__` most likely won't work as we cannot import the package in setup time as at that time some dependencies are still missing and it crashes if you install the package in blank OS.
it is also why we have this dynamic data parsing instead of import package:
https://github.com/PyTorchLightning/pytorch-lightning/blob/01f5f99919e9828c088ba4a39e6d492f19f49c44/setup.py#L34

**Comment by k4black** [comment]
As I remember, starting with _some_ version of the setuptools they use python AST to get `attr:` to cope with issue you described  
But, I'll check
