### ISSUE TITLE
problem when I fit the model

### ISSUE THREAD

**Issue by Dhuha1** [PyTorchLightning/pytorch-lightning#10996]
Hello,
I have a problem when I try to fit the model. the following error is appear when I use the pytorch lightning version 0.7.5

`MisconfigurationException: You have passed in a `test_dataloader()` but have not defined `test_step()`.`

![image](https://user-images.githubusercontent.com/93883815/145234719-b930a09a-c875-4234-b595-ba7ff3ac1034.png)

and if I don't use this version and use the latest version I have another problem specially when I run (tokenizer.decode) . The error is shown below:
`AttributeError: 'NoneType' object has no attribute 'batch_encode_plus' `

and when I search about the problem it is recommended to use the version 0.7.5. So, I think the latest version is not suitable because this code is written before more than a year. the used code I find it here
 https://github.com/priya-dwivedi/Deep-Learning/blob/master/wikihow-fine-tuning-T5/Tune_T5_WikiHow-Github.ipynb

could you please see the code and guide me for the suitable version or if you know what is the cause of  these errors.
I wait for your reply

**Comment by rohitgr7** [comment]
First error must be coming up because there might not be a `test_step` method overridden in the datamodule which is pretty much explainable from the error message.

The second one seems to be related to the huggingface tokenizers not being initialized correctly.

v0.7.5 is very old. Can you try the latest version? Give it a try, we can help you with any errors you face during conversion.
