### ISSUE TITLE
Suggest to add docs for trainer.logger.experiment.add_image()

### ISSUE THREAD

**Issue by smartdanny** [PyTorchLightning/pytorch-lightning#11013]
## 📚 Documentation

Was just dealing this for like an hour trying to figure out how to save confusion matrices in tensorboard from pytorch lightning. 

I was using this as an example, https://github.com/PyTorchLightning/lightning-bolts/blob/master/pl_bolts/callbacks/vision/image_generation.py.

But, when trying to plot something from matplotlib you get an opaque error, something like "TypeError: Cannot handle this data type: (1, 1, 720), |u1. Which doesnt even make sense since my np array is (720, 1080, 3).

Apparently the issue was just that it needs to be (3, x, x), channel first (I just permuted it).

This should either return some error, be caught in a try catch, or be documented. Ill try to do it next week if I have time and nobodys done it yet. pretty easy issue.

cc @borda @rohitgr7 @awaelchli @edward-io

**Comment by Nesqulck** [comment]
If I understood your case correctly, you can also take a look at the [TensorboardX SummaryWriter documentation](https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_image) which is the underlying Tensorboard logger accessible by trainer.logger.experiment.

In add_image(), you can specify the `dataformats` parameter which could be either `"CHW"`, `"HWC"` or `"HW"`. In your case, you could use `"HWC"` and remove the permutation. So, it is more of a TensorboardX issue than PL. However, I agree that there should be a much more clearer documentation as it was not clear for me either that it is using TensorboardX under the hood. Perhaps a simple reference to the TensorboardX documentation would suffice?

Tip: You can use the SummaryWriter's add_figure() to plot directly from matplotlib into tensorboard without converting a figure into a numpy array.

**Comment by ananthsub** [comment]
The experiment property is incredibly ambiguous & meaningless from an interface guarantee, which is why I've proposed deprecating it: https://github.com/PyTorchLightning/pytorch-lightning/issues/11234

It makes much more sense for the TensorboardLogger to make the summary writer part of its public API. 
So if you know you're using tensorboard, you should be able to do something like this instead:
```py
logger.summary_writer.add_image
```
this code can be better typechecked and is more readable to me to figure out what's happening compared to:
```py
logger.experiment.add_image
```

**Comment by awaelchli** [comment]
Instead of documenting `trainer.logger.experiment.add_image()`, which would just be about duplicating the docs of `SummaryWriter.add_image`, I would rather instead improve documentation for the common `LightningLoggerBase.log_image ` API and their direct implementations that were recently added. And more media types can be supported in the future, we just need help from the community finding the right API that satisfies most use cases and loggers.

**Comment by SEUleaderYang** [comment]
Hello, I recently encountered some confusion when using this function. Because the tensor range of pytorch network output is 0~1, but we tend to multiply each pixel value by 255 when saving images, it seems that "logger.experiment.add_images" does not need the operation of multiplying by 255, is that right?
