### ISSUE TITLE
multinode training: uneven training data and torchdata

### ISSUE THREAD

**Issue by tmbdev** [PyTorchLightning/pytorch-lightning#11255]
Right now, Lightning seems to assume the exact same number of training samples in each node. This is a problem when trying to train with true epochs, since the number of nodes in a training job usually doesn't divide the number of samples. The problem is compounded when the data is sharded and iterable datasets are used (as in torchdata and webdataset). The usual workaround is to just either omit samples or replicate training samples in each epoch to make it evenly divisible.

PyTorch 1.10 addresses this issue much better with the torch.distributed.algorithms.join, allowing dataloaderrs on different nodes to return different amounts of data.

Unfortunately, Lightning doesn't seem to have any support for this right now.

It would be nice if Lightning could support the use of Join, perhaps making it optional via a configuration parameter in the trainer.

cc @borda @justusschock @awaelchli @ninginthecloud

**Comment by ananthsub** [comment]
We have previously explored using `join`: https://github.com/PyTorchLightning/pytorch-lightning/issues/3325 . 
However, the manner in which join tracks collectives can quickly run into issues with other collectives that run in the forward pass / training_step. 

I'm going to close this issue in order to consolidate discussion on the one I listed above.

FWIW, this isn't unique to multi-node training. It to single-node multi-process training as well, where we have an uneven end of data.
