### ISSUE TITLE
Mentioning the predict_dataloader in the LightningDataModule

### ISSUE THREAD

**Issue by rasbt** [PyTorchLightning/pytorch-lightning#11636]
## 📚 Documentation

On the following page (On the following page (https://pytorch-lightning.readthedocs.io/en/latest/extensions/datamodules.html#predict-dataloader) I stumbled upon the  `predict_dataloader()` method.

Should we reference is as an option in the `LightningDataModule` method doc?
I.e., currently it has the section

https://github.com/PyTorchLightning/pytorch-lightning/blob/b3c0f121cabe0c9559970eb12394446aa5955cc8/pytorch_lightning/core/datamodule.py#L54-L63

but I think `predict_dataloader()` is implemented elsewhere as a hook? So, I can also see a point for not mentioning it here. What do you think?

cc @borda @rohitgr7

**Comment by rohitgr7** [comment]
yes! 
`predict_dataloader` and all others are common hooks for LDM and LM.

I think we can just remove this sub-section completely. Since not just `predict_dataloader` but `on_load_checkpoint/on_save_checkpoint/transfer_batch_to_device` are also not there. since it adds an overhead for anyone to remember to update this section in case some hooks are added/removed/modified.

LDM already has an extensive [separate doc](https://pytorch-lightning.readthedocs.io/en/latest/extensions/datamodules.html) that tells everything one needs to know.

**Comment by bhadreshpsavani** [comment]
Hello,
Can I create a PR for these documentation changes?

**Comment by tchaton** [comment]
Hey @bhadreshpsavani,

Yes, please.
