### ISSUE TITLE
[RFC] Deprecate `CheckpointHooks` off `LightningDataModule`, `PrecisionPlugin`

### ISSUE THREAD

**Issue by jjenniferdai** [PyTorchLightning/pytorch-lightning#11824]
## Proposed refactor

Following the addition and alignment of `Stateful` API in issue #11429, deprecate `CheckpointHooks` `on_save/load_checkpoint(checkpoint_dict)` off `LightningDataModule` and `PrecisionPlugin`.

### Motivation

Now that `LightningDataModule` and `PrecisionPlugin` can contribute and load their own component state with `Stateful` APIs, I don't think there's much use cases where these components need access to edit or peek at other component states in the checkpoint dictionary - could we deprecate `CheckpointHooks` off these components?

### Pitch

Deprecate `CheckpointHooks` off `LightningDataModule` and `PrecisionPlugin`.
Issue deprecation warning if `on_save/load_checkpoint` are overridden, remove in v1.8.

### Additional context

issue #11429 

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @justusschock @awaelchli @akihironitta @rohitgr7 @ananthsub @ninginthecloud @tchaton

**Comment by awaelchli** [comment]
From the context I understand that you are proposing to replace the `on_x_checkpoint` with `state_dict()` and `load_state_dict()` on the LightningDataModule. But this is not in line with the hook language and design principle behind Lightning IMO.

- `state_dict()` on a `nn.Module` has a default implementation. That makes it not a hook. 
- If one overrides `state_dict` to add to the returned dict, one has to call super(), something that does not really exist in Lightning, because (almost) every method relevant to the user is a hook. Lightning clearly wants to avoid exposing this pattern to minimize the number of times the user has to ask herself "do I need to call super here or not??". 
- `on_load_checkpoint/on_save_checkpoint` expresses in simple and unambiguous words **when** this hook is called and **what** it is supposed to do. `state_dict()` only expresses the latter.

While it may not seem like a big deal to remove it from the LightningDataModule, it definitely would be for the LightningModule IMO. And if we only have it on the LM, then we would again have to answer the question the users have:
Q: LM has the on_x_checkpoint hook but LDM does not. Can we add it for consistency? It would be very useful!
A: No, but you can use state_dict() on the LDM
Q: Why is it state_dict on LDM but on LM we have a different one?
A: ...

With these concerns I strongly recommend against going with this RFC. My same argument applies to Callback and LM.
(not saying we shouldn't do the Stateful changes)

**Comment by jjenniferdai** [comment]
On the same page about adding `Stateful` consistency across components (issue #11429), keeping `on_save/load_checkpoint` for LM, Callbacks, and deprecating `on_save/load_checkpoint` for PrecisionPlugin.

re: keeping LDM `on_save/load_checkpoint`:
I feel the main question is are there any use cases where data state needs to edit or peek at other component states? I haven't seen any myself and can't think of examples where this is needed.
- If there are no use cases, it's leaner to just offer `Stateful` PyTorch convention. We shouldn't offer these hooks if they don't add any value just for the sake of consistency with LM hooks.
- If there are use cases, we should keep these hooks for LDM.

> If one overrides `state_dict` to add to the returned dict, one has to call super()

mind clarifying? With the Stateful changes users would just need to implement `state_dict/load_state_dict` in their own components, there's no need for any super() calls

> `on_load_checkpoint/on_save_checkpoint` expresses in simple and unambiguous words when this hook is called and what it is supposed to do. `state_dict()` only expresses the latter.

I guess the hook name might be a bit more explicit about the **when**, but I feel `state_dict/load_state_dict` PyTorch convention carries this **when** implication itself - everyone calls these when they save and load states.

**Comment by awaelchli** [comment]
My fear is that #11893 will be used as a motivation to remove the same hooks on the LM and callbacks. Furthermore, #12232  will send the signal that since we have state_dict() on the Callback now, we won't need the `on_*_checkpoint` hooks anymore there, and they get removed. I'm trying to fight back on this and I'm trying to explain there is a difference between the state dict methods and the hook that gets called by the Trainer, and the fact that we need **both** of them.

**Comment by jjenniferdai** [comment]
> there is a difference between the state dict methods and the hook that gets called by the Trainer

totally agree, this is the distinction from the Stateful issue #11429:
> 1. independently contributing/loading one’s own local component state (aligning with PyTorch primitives: state_dict/load_state_dict)
> 2. operating and depending on global component state (Lightning CheckpointHooks: on_save/load_checkpoint)

---
> and the fact that we need both of them

This issue is for auditing, for each component, if we need to additionally offer 2.
- LM deprecation was **not** proposed because we've seen plenty of use-cases for customizing model save/load, and 2. also allows this without having to override nn.Module state_dict/load_state_dict.
- Callback deprecation was **not** proposed because a user could be doing anything in their own Callbacks, it makes sense to offer 2. if the callback needs access to component states. 
- LDM and precision plugin deprecation were proposed because we could not see any use cases where these components would need to edit or peek at other component states. from above,
> If there are no use cases, it's leaner to just offer Stateful PyTorch convention. We shouldn't offer these hooks if they don't add any value just for the sake of consistency with LM hooks.
> If there are use cases, we should keep these hooks for LDM.
