### ISSUE TITLE
Progress bar does not update properly with steps

### ISSUE THREAD

**Issue by amin-nejad** [PyTorchLightning/pytorch-lightning#11876]
## 🐛 Bug

When `max_steps` is specified to the Trainer, the total value of the trainer becomes the number of data points rather than the number of batches. However the increments in the progress bar are still done in number of batches which means the bar does not move properly.

### To Reproduce

Train a model and specify `max_steps` to the `Trainer` with `progress_bar_refresh_rate=1`. The progress bar should update every single step, which it does, but it does not take into account the batch size. In the boring model, the data size is 64 and the batch size is 2. This means there should be 32 batches but the progress bar is out of 64. However every batch only goes up 1 unit on the progress bar until the very last batch. So the penultimate batch is 32/64 and then the final batch is 64/64.

https://colab.research.google.com/drive/12H5mJGG_kWYBW4gf58pDWPtM5Z3TMGiZ?usp=sharing

### Expected behavior

The expected behaviour is that every batch should increment one unit on the progress bar and the total number of units should be the total number of batches in the training dataloader

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.5.10
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           # 1 SMP Tue Dec 7 09:58:10 PST 2021

cc @SeanNaren @kaushikb11 @awaelchli @rohitgr7

**Comment by awaelchli** [comment]
Hello
I looked at your code sample in the link and I am struggling to find any issues at all. I added a `time.sleep(0.5) ` into the training- and validation steps to observe the steps in the bar, and they all increase properly throughout until the end. 

> The progress bar should update every single step, which it does, but it does not take into account the batch size. In the boring model, the data size is 64 and the batch size is 2. This means there should be 32 batches but the progress bar is out of 64

In this example, there are two dataloaders being used, one for training and one for validation. Both have 64 samples and a batch size of 2, which means in one epoch there will be a total of 64 / 2  + 64 / 2 = 64 batches. If you disable the validation by setting limit_val_batches=0, you will see 64 / 2 as the total.

Furthermore, in your first section you set max_steps=31, which is one short of the size of the training dataloader. Since the training epoch doesn't get completed, the loop exits earlier and does NOT perform validation which is expected behavior. Hence the progress bar stops there. 

In the second section, you set max_epochs=32 and this is just the number of steps to run through a full training epoch. This means the loop will also perform validation for the extra 32 batches in the validation dataloader. 

To the best of my understanding, I can't see a bug here. Can you check my observations?
