### ISSUE TITLE
Fix inconsistency when user specifies `weights_save_path`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#12254]
### Background

Currently, when the user specifies `weights_save_path` we have inconsistent behavior as to the path where we actually save the checkpoints. 

If we have no loggers, we save to `weights_save_path/checkpoints` (line 587)
If we have one logger, we save to `weights_save_path/name/version/checkpoints`
If we have multiple loggers, we save to `weights_save_path/name1_name2/version1_version2/checkpoints`

https://github.com/PyTorchLightning/pytorch-lightning/blob/2360049744667c21a532a2cb7bee290e002a9698/pytorch_lightning/callbacks/model_checkpoint.py#L572-L587

### Proposed refactor

Let's always use the path `weights_save_path/checkpoints` , like we do for the case when there is no Logger: https://github.com/PyTorchLightning/pytorch-lightning/blob/5df519572f78ae5e23b0aab18fcbda06df7ff8dd/pytorch_lightning/callbacks/model_checkpoint.py#L607

### Motivation

* It doesn't make sense to store the checkpoints under a path containing the loggers' names and versions, because we are not writing to the logger at all. We are writing to the `weights_save_path` provided by the user. 
* For the user it is a strange experience that he/she provides a `weights_save_path`, but depending on whether there is a logger or not, the path gets changed
* The concatenation of the logger names and versions has an awkward look to it and should be fixed. It is a relic of the deprecated `LoggerCollection`.

Why should we do this even though `weights_save_path` has been deprecated?
1. It is the right experience for the user
2. It will clean up a particularly confusing part of the code and make it much easier to understand
3. It will make implementation of https://github.com/PyTorchLightning/pytorch-lightning/issues/12177 and https://github.com/PyTorchLightning/pytorch-lightning/issues/12028 a lot simpler

cc @awaelchli @edward-io @borda @ananthsub @rohitgr7 @kamil-kaczmarek @Raalsky @Blaizzy @ninginthecloud

**Comment by daniellepintz** [comment]
Updated the title and description

**Comment by awaelchli** [comment]
It probably makes sense to do this for long term. 


As usual, I will jump in to give a small history lecture 🤣
weights_save_path was previously used to save mainly two things:
1. a special checkpoint when interrupting training with e.g. the Ctrl+C signal
2. a special checkpoint when receiving a SLURM interrupt signal

(1) got replaced by fault-tolerant training and (2) is currently being changed to use default_root_dir.
If I remember correctly, the motivation behind using weights_save_path also in the ModelCheckpoint was for convenience, in that you had to only change a trainer arg instead of instantiating a ModelCheckpoint with a custom dir_path.
