### ISSUE TITLE
Multi gpu training guide points to a dead page.

### ISSUE THREAD

**Issue by psridhar-asapp** [PyTorchLightning/pytorch-lightning#12558]
This link seems dead now https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html

cc @borda @rohitgr7

**Comment by akihironitta** [comment]
Hi @psridhar-asapp, thanks for reporting this! Recently, we've restructured the docs, and some of the links may be 404. Could I ask where you've got the link?

**Comment by kaushikb11** [comment]
Hey @psridhar-asapp,

Do let us know where you got the link.

Here are the updated links:
1. https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html#distributed-modes
2. https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html

**Comment by rohitgr7** [comment]
probably seo will be improved with time since these are new docs.

you can still search for let's say `register_buffer` in the docs and get the correct page.
This is what I did and got: https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu.html#init-tensors-using-type-as-and-register-buffer

:)
