### ISSUE TITLE
Upgrading from 1.5.10 to 1.6.0 causes the PyTorch WandB logger to produce multiple experiments

### ISSUE THREAD

**Issue by amorehead** [PyTorchLightning/pytorch-lightning#12583]
## 🐛 Bug

Upgrading from 1.5.10 to 1.6.0 causes the PyTorch WandB logger to produce multiple experiments.

### Expected behavior

Lightning should create only a single experiment for a single training job when logging with DDP and Weights & Biases (WandB) across multiple compute nodes and GPUs.

### Additional context

This only occurs on my LSF compute cluster when I upgrade to PyTorch Lightning 1.6.0. Downgrading to version 1.5.10 resolves the issue.

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by awaelchli** [comment]
Hey @amorehead 

Are you running the latest version of wandb? Because version >= 0.12.10 had some improvements that were integrated with PL 1.6. 

On the other hand, the source of the problem might be that the rank_zero_only doesn't work properly because the rank variable from LSF is not included here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/2ee187ea1375a75aaf04dea29c7532eb7d037b0e/pytorch_lightning/utilities/rank_zero.py#L39-L42

We would probably have to include the variable `JSM_NAMESPACE_RANK`.

**Comment by awaelchli** [comment]
Could you give my patch a try?

`pip install git+https://github.com/PyTorchLightning/pytorch-lightning@bugfix/rank-zero-lsf`

(or checkout the branch rank-zero-lsf if you have the PL source locally)

**Comment by amorehead** [comment]
@awaelchli, even with version 0.12.11 of WandB, version 1.6.0 of PyTorch Lightning creates duplicate experiments in WandB's online logging platform. However, with your patch, my issues with version 1.6.0 of Lightning are resolved! Thank you for your help and quick reply/solution

**Comment by awaelchli** [comment]
@amorehead great! Happy to help. 
I'll keep the issue open until my fix is merged.
