### ISSUE TITLE
How to change the schedule of the built-in PyTorch Profiler?

### ISSUE THREAD

**Issue by dpaleka** [PyTorchLightning/pytorch-lightning#12656]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/12611

<div type='discussions-op-text'>

<sup>Originally posted by **dpaleka** April  4, 2022</sup>
When using PyTorch Profiler in plain PyTorch, one can change the profiling schedule, see e.g. the arguments in the first snippet  [here](https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/):
``` 
with torch.profiler.profile(
    schedule=torch.profiler.schedule(
        wait=2,
        warmup=2,
        active=6,
        repeat=1),
    on_trace_ready=tensorboard_trace_handler,
    with_stack=True
) as profiler:
```

How to do this in PyTorch Lightning? There is nothing about the profiler schedule in the [docs](https://pytorch-lightning.readthedocs.io/en/stable/advanced/profiler.html).</div>

cc @carmocca @kaushikb11 @ninginthecloud @rohitgr7

**Comment by laserkelvin** [comment]
I'm encountering the same problem: in my case I've tried to pass the schedule arguments as kwargs to `PyTorchProfiler`:

```python
profiler = PyTorchProfiler(
    dirpath=profile_run_path,
    group_by_input_shapes=True,
    wait=2,
    warmup=2,
    active=10,
    repeat=3,
    profile_memory=True,
    with_stack=True,
    with_flops=True,
)
...
trainer = Trainer(..., profiler=profiler)
```

With this I still only get three steps in the training trace with one cycle, no wait or warm up steps.

In principle you could probably get the desired effect through a `custom_processing_step`, but that would be undesirable since the profiling scope/output is exactly what I wanted, if only it would work on my schedule.

**Comment by carmocca** [comment]
You can pass:

```python
profiler = PyTorchProfiler(schedule=torch.profiler.schedule(wait=1, warmup=1, active=3))
```

with your custom schedule instance
