### ISSUE TITLE
precision=16 doesn't work

### ISSUE THREAD

**Issue by lg2578** [PyTorchLightning/pytorch-lightning#13073]
my code is here:
https://www.kaggle.com/code/lezilv/digit-recognition-pytorch
I've tried update to 1.6.3 and torch==1.11.0
whether or not turn on/off precision=16, the epoch time is same.
any one can tell me what's happened

cc @carmocca @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by awaelchli** [comment]
Hi @lg2578 
The [mixed precision](https://github.com/PyTorchLightning/pytorch-lightning/discussions) does not guarantee you a speed up always, but often times it reduces the memory footprint. 
I'm not sure what you expected or what you have read about it, but we would need more information about your issue. Otherwise the issue will be closed. If you have general questions about how to use mixed precision, you can go to [Discussions](https://github.com/PyTorchLightning/pytorch-lightning/discussions) and post your question there.

**Comment by justusschock** [comment]
Also note, that not all GPUs do support mixed precision training at all. Specifically, the older P100 which you apparently get on kaggle don't

**Comment by lg2578** [comment]
> Also note, that not all GPUs do support mixed precision training at all. Specifically, the older P100 which you apparently get on kaggle don't

thanks very much.
