### ISSUE TITLE
Dockerize test env

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#1372]
## 🚀 Feature

the simples way for speedup builds is have a docker image with all dependencies then preserving pip cache, that means we will create a docker image which will be pulled

### Motivation

for that, the simples way is hawing it id docker hub as it is a native location for almost all CI
these "devel-lightning" docker images can be simply used by any contributor for testing lol

### Pitch

we may also have a docker image with installed lightning and all requirements which would make the starting with lightning even easier and it would be also useful for people working on a production

### Additional context

later I may configure a cron do this docker build every week

**Comment by luiscape** [comment]
Given that Lightning doesn't have a lot of dependencies, I think this is a good idea. The one risk is that the image becomes stale when dependencies change and the image isn't updated. (One can solve that by updating the image every time there's an update in a dependency.)

On a related note, it seems to be that we should pin all dependency versions instead of having them use comparison terms like `>`. It's hard to know which exact version will be installed when the image is built and it also carries the risk of a dependency update breaking things.

**Comment by Borda** [comment]
We will have a weekly builds and also we keep their `pip install requirements.txt` so if there is something new (missing in the Docker image) it will be installed standard way till new image is built...

**Comment by Borda** [comment]
done in #1584 #2779
