### ISSUE TITLE
give "validation sanity check" flag for "validation_epoch_end" & "validation_step"

### ISSUE THREAD

**Issue by davinnovation** [PyTorchLightning/pytorch-lightning#1391]
### Motivation
 When using some custom saver, logger in validation function (`validation_epoch_end`, `validation_step`), with Trainer.fit(), it always execute `validation sanity check` so mess log comes out.

### Pitch
```python
def validation_step(self, batch, batch_nb, sanity_check):
   if sanity_check:
      ...
def validation_epoch_end(self, outputs, sanity_check):
   if sanity_check:
      ...
```
or
```python
def validation_step(self, batch, batch_nb):
   if self.sanity_check:
      ...
def validation_epoch_end(self, outputs):
   if self.sanity_check:
      ...
```
### Alternatives

None

### Additional context

None

**Comment by awaelchli** [comment]
This could be addressed with the Trainer states: #1633

**Comment by ZhaofengWu** [comment]
@awaelchli I'm looking at #1633 and the merged PR #2541. What's the training state that corresponds to this usage? Is it `TrainerState.INITIALIZING`?

**Comment by ZhaofengWu** [comment]
Nvm, found this flag `trainer.running_sanity_check`.

**Comment by noamzilo** [comment]
![1](https://user-images.githubusercontent.com/4740186/104914752-4441dc00-5998-11eb-9fc5-54cf7b943e45.jpg)
![2](https://user-images.githubusercontent.com/4740186/104914758-460b9f80-5998-11eb-8176-30c7660bf01a.jpg)

I am seeing the following problem and have no elegant way of fixing it: it appears as if val loss < train loss, but in reality, the val_step happens one step before the train_step because of the sanity step.

would be nice if one could turn off all logging for the validation step.

This also interrupts some of Tensorboard's other functionality in some cases, such as add_image which expect one to not already exist.

**Comment by noamzilo** [comment]
Is there a way to disable .log and .logger for the sanity step using the framework in an elegant way?

**Comment by awaelchli** [comment]
@noamzilo how about we provide `logger.enable()` and `logger.disable() `methods?
Then the user could call these for example in the LightningModule, to temporarily disable logging. 
For example: 

```python
def on sanity_check_start(self):
    self.logger.disable()

def on_sanity_check_end(self):
    self.logger.enable() 
```

**Comment by noamzilo** [comment]
> 
> 
> @noamzilo how about we provide `logger.enable()` and `logger.disable() `methods?
> Then the user could call these for example in the LightningModule, to temporarily disable logging.
> For example:
> 
> ```python
> def on sanity_check_start(self):
>     self.logger.disable()
> 
> def on_sanity_check_end(self):
>     self.logger.enable() 
> ```

sounds great :)

___

In this opportunity, I would like to raise a concern I found, not sure if I am doing something wrong:

![2](https://user-images.githubusercontent.com/4740186/104921080-891e4080-59a1-11eb-81fa-d89645eec414.jpg)
![1](https://user-images.githubusercontent.com/4740186/104921085-89b6d700-59a1-11eb-9374-726b78b528b2.jpg)

These are plotted using

`tb.add_scalars("losses", {"val_loss": loss}, global_step=self.current_epoch)`
`tb.add_scalars("losses", {"train_loss": loss}, global_step=self.current_epoch)`

with

trainer = Trainer(
            overfit_batches=True,
    )
and a single sample per batch.

This configuration should mean that the training loss should always equal the validation loss.

However, as the graphs show (and I validated this with the debugger), the trainins loss lags by 1 epoch after the val loss.
They are exactly equal, but with a lag.

using `tb.add_scalars("losses", {"train_loss": loss}, global_step=self.current_epoch - 1)` solves this, but I doubt that was the original designers intention.


Am I doing something wrong? Did I find a bug?

Initially, I thought this was due to the sanity epoch, but it seems this isn't the case.

**Comment by AtomScott** [comment]
@noamzilo @awaelchli has this implemented? 

```python
def on sanity_check_start(self):
    self.logger.disable()

def on_sanity_check_end(self):
    self.logger.enable() 

```

If not we shouldn't reopen this issue? This is a feature that I would use daily and also something were I had to write my own workaround so I don't mind getting my own hands dirty.

**Comment by jmerkow** [comment]
@noamzilo @awaelchli Bumping this issue....

@ZhaofengWu how do you access this flag from a PL module?

**Comment by ananthsub** [comment]
you can do `if self.trainer.sanity_checking` inside the LightningModule

**Comment by brendanartley** [comment]
Is there any way of accessing the `trainer.sanity_checking` variable in a custom callback?

```
class CustomCallback(pl.Callback):
  def __init__(self):
    super().__init__()

  def on_validation_epoch_end(self, trainer, module):
    if not trainer.sanity_checking:
        return
    else:
        # do something here
```

This throws the following error.

```
AttributeError: 'Trainer' object has no attribute 'running_sanity_check'
```

**Comment by klieret** [comment]
Are you sure you didn't mistype `trainer.running_sanity_check` instead of `trainer.sanity_checking`? I can access the variable just as in your code snippet.
