### ISSUE TITLE
horovod cicd tests are failing on ubuntu 18.04 python 3.6 latest

### ISSUE THREAD

**Issue by yukw777** [PyTorchLightning/pytorch-lightning#1620]
## 🐛 Bug

The failed job: https://github.com/PyTorchLightning/pytorch-lightning/runs/620109522

We see two errors:
1. `RuntimeError: Failed to determine if NCCL support has been built. Run again with --verbose for more details.`
1. `ImportError: /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE`

My hunch is that both are caused by the same horovod compilation issue.

Another thing to note is that the same tests are passing on ubuntu 18.04 python 3.6 **minimal**.

@tgaddair maybe you have an idea?

### To Reproduce

Run the cicd test suite.

**Comment by tgaddair** [comment]
Hey @yukw777, I have seen this issue before.  If I remember correctly, it is related to having a corrupted pip cache.  I would suggest commenting out the step "Cache pip" and see if that fixes the issue.

My suspicion is that the CI system used a cached version of Horovod, but reinstalled a new version of PyTorch.  Because Horovod is built against a specific version of PyTorch, that can lead to these incompatibilities and runtime if the PyTorch version is swapped out.

If I remember correctly, the pip cache didn't save that much time, so it may be worth removing it.

**Comment by yukw777** [comment]
@Borda @williamFalcon shall I send you guys a PR that removes the pip caching step for now?

**Comment by Borda** [comment]
check #1558

**Comment by Borda** [comment]
> My suspicion is that the CI system used a cached version of Horovod, but reinstalled a new version of PyTorch. Because Horovod is built against a specific version of PyTorch, that can lead to these incompatibilities and runtime if the PyTorch version is swapped out.

that would perfectly fit our case as Horovod has been adding fro about two weeks and just last week new PyTorch was released so other cache stuck with Horovod and reinstalled only PyTorch as Horovod version hold...

**Comment by yukw777** [comment]
#1558 should fix it for now. Currently there's no way to manually invalidate the cache, so whenever this happens again, we can add a version number to the cache key and bump that up to invalidate the old cache.
