### ISSUE TITLE
name 'IProgress' is not defined

### ISSUE THREAD

**Issue by drozzy** [PyTorchLightning/pytorch-lightning#1687]
name 'IProgress' is not defined when running from Jupyter notebook.

**Comment by olineumann** [comment]
Did you tried to install ipywidgets?

https://ipywidgets.readthedocs.io/en/latest/user_install.html

**Comment by williamFalcon** [comment]
should we try catch this? and change usage + warn user when this happens?

**Comment by olineumann** [comment]
Isn't it only tqdm.auto which uses ipywidgets to display a progress bar? That we only use here:
https://github.com/PyTorchLightning/pytorch-lightning/search?q=tqdm.auto&unscoped_q=tqdm.auto

Maybe it should be changed in tqdm.auto to not take IProgess if ipywidgets is not installed. There are already some checks:
https://github.com/tqdm/tqdm/blob/master/tqdm/autonotebook.py

But I had a similar problem when using jupyter lab and I had to install nodejs for it (which I wanted to avoid) but found no way of disable tqdm.auto taking IProgress. In my case it didn't crashed but no progress bar were displayed. If someone knows a way of overwriting the tqdm.auto selection let me know. Otherwise I think the checks should be better or there should be a way of overwriting the tqdm.auto selection. (In my opinion)

**Comment by drozzy** [comment]
I am doing:
`from tqdm import tqdm`
and it seems to work.

**Comment by Borda** [comment]
I do not think we want to add `ipywidgets` as dependency bu we can do similar check on our side too
@olineumann mind send PR?
