### ISSUE TITLE
model load error when the module is defined with extrat positional auguments

### ISSUE THREAD

**Issue by jxchen01** [PyTorchLightning/pytorch-lightning#1711]
## 🐛 Bug

https://github.com/PyTorchLightning/pytorch-lightning/blob/0.7.5/pytorch_lightning/core/lightning.py#L1552

When using ddp, this function will throw an error if the pl module is defined with extra positional arguments.

### To Reproduce

1. define a pl module with extra positional arguments:
'''
class My_Classifier(pl.LightningModule):

    def __init__(self, model_params: dict, train_params: dict) -> None:
'''

2. Train the model with `ddp`
3. At some point, a model reloading is triggered
4. Then, this function will have an error:

https://github.com/PyTorchLightning/pytorch-lightning/blob/0.7.5/pytorch_lightning/core/lightning.py#L1552

model = cls(*model_args, *args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'model_params' and 'train_params'

### Expected behavior

Either prevent using extra positional arguments when using ddp, or support more args others than  hparams

### Environment

* CUDA:
        - GPU:
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
                - Tesla V100-SXM2-32GB
        - available:         True
        - version:           10.1
* Packages:
        - numpy:             1.18.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.4.0
        - pytorch-lightning: 0.7.5
        - tensorboard:       2.1.1
        - tqdm:              4.45.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                -
        - processor:         x86_64
        - python:            3.7.7
        - version:           #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019

**Comment by Borda** [comment]
@cmpute mind have a look?

**Comment by cmpute** [comment]
In my understanding, right now the trainer must have no argument or only `hparam` argument except for other arguments when it's used in DDP, because lightning only handles the hparams when loading temporary checkpoint: https://github.com/PyTorchLightning/pytorch-lightning/blob/e6b34ef90d5f3eac70154b305b476614a64f1981/pytorch_lightning/trainer/distrib_data_parallel.py#L400

To solve this problem, constructor parameters in lightning module should also be saved into the temporary checkpoint and loaded when DDP reconstruct the module. But this will be an additional feature. My personal reference is to wrap all parameters needed into the `hparam` argument.

**Comment by nikraina** [comment]
I also got stuck in the similar issue.. I was trying to make customizable batch size for train/test/val dataloaders among other things(the goal was to reuse core code with different training setups) so that I can re-use the code with minimum changes to core training code.

Although not a clean solution, I ended up using setters to set these custom configs, and calling them before Trainer.fit(my_model)

`
class MyModel(LightningModule):
    def __init__(self):
        <your_code_here>

    def set_train_batch_size(self, train_batch_size):
        self.train_batch_size = train_batch_size

#Now use this self.train_batch_size in your train dataloader

#your model loading code will look simpler now
model_1 = MyModel.load_from_checkpoint(<path_to_the_checkpointed_model>)

`

Please let us know if there is better way of doing this.

**Comment by williamFalcon** [comment]
you can add more arguments to the load call... take a look at the docs

**Comment by nikraina** [comment]
> load
sorry, should have given more information, my load call is encapsulated in the prepare_data()

my goal is to have a Model class which i can create different instances of, and then use different configs such as datasources/batchsize etc among others, without changing the Model class, but controlling these things when i initialize the object form the class
