### ISSUE TITLE
Is it ok to translate the Docs into Chinese?

### ISSUE THREAD

**Issue by Xunzhuo** [PyTorchLightning/pytorch-lightning#2001]
### Motivation
Let more Chinese Deep Learning lovers to know Pytorch-lightning

**Comment by Borda** [comment]
Sure, let us check how the multi-language Docs works...
cc: @PyTorchLightning/core-contributors

**Comment by Borda** [comment]
@Xunzhuo mind check this tutorial?
https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

**Comment by Xunzhuo** [comment]
Sure I`ll read it

**Comment by Borda** [comment]
@Xunzhuo why have you closed this issue, no more interested in Chinese translation?

**Comment by Xunzhuo** [comment]
Ohhh Sorry maybe I click the wrong button "Close and Comment" by mistake~
I`ll read the file and translate it soon

Jirka Borovec <notifications@github.com> 于2020年6月3日周三 下午1:58写道：

**Comment by Xunzhuo** [comment]
Sorry I may click the wrong button "Close and Comment" by mistake~ I will read the file and 
 try to translate it into Chinese

**Comment by edenlightning** [comment]
Thank you @Xunzhuo for brining this up! We would love to make AI and Lightning specifically more accessible to everyone. That being said, doc maintenance is not trivial even in a single language. Since manual translation seems like way to much work, we can look into machine translating docs to some primary languages, and have a lead community member in charge of each lang. We will hold on this until our API is stable enough (v1.0.0)

**Comment by WD2314** [comment]
Looking forward to the Chinese version of the doc!
