### ISSUE TITLE
Early Stopping Callback not working

### ISSUE THREAD

**Issue by Dunrar** [PyTorchLightning/pytorch-lightning#2051]
## 🐛 Bug

See #2038. Early stopping stopped too early when using Lightning 0.7.7.dev0 (only on a Slurm cluster, not locally, but I might have been using slightly different Lightning versions). After upgrading to current master, early stopping does not work anymore, at all. I had a similar problem because of not having a val_step (see #1201), maybe something  like that crept back in. 
### To Reproduce

See #2038 but use current master

**Comment by Dunrar** [comment]
Little update: In training_loop.py line 379 `should_stop = self.early_stop_callback.on_validation_end(self, self.get_model())` always returns None because early_stop_callback.on_validation_end() has no return. Returning `self._run_early_stopping_check(trainer, pl_module)` re-enables early stopping.

**Comment by awaelchli** [comment]
Early stopping is under somewhat heavy construction currently :)

> Early stopping stopped too early when using Lightning 0.7.7.dev0

I think there was an issue with patience, and the solution was to scale patience by some factor.
#2038 

> always returns None because early_stop_callback.on_validation_end() has no return. 

This will be fixed soon. The PR here #1504 is making it so that the checks run on validation end and also after the checkpointing. If you like, you can have a look and check if the changes already work for you (some tests are still failing though).

**Comment by Dunrar** [comment]
Ah, okay, thank you!

**Comment by wassname** [comment]
Yeah I just found it, there's a bug where it init -inf when using min, and +inf when max, should be the other way round.

**Comment by philip30** [comment]
I modified the code by myself and found another bug. Somehow it is called twice by the training loop! Once in 793 and 363

**Comment by awaelchli** [comment]
I think this is getting fixed in #1504 . it getting called twice is a known issue.

**Comment by williamFalcon** [comment]
Closed via #2119
