### ISSUE TITLE
wandLogger().name is None in DDP mode

### ISSUE THREAD

**Issue by sshleifer** [PyTorchLightning/pytorch-lightning#2131]
If you remove [line 54](https://github.com/PyTorchLightning/pytorch-lightning/blob/8ca8336ce52ee7379f4d399520636143eb31018b/pytorch_lightning/trainer/callback_config.py#L54), everything works.

When you're not in ddp mode, this is not an issue.

**Comment by williamFalcon** [comment]
@vanpelt any thoughts on this?

**Comment by Borda** [comment]
@sshleifer it is caused by missing `self._experiment` 
https://github.com/PyTorchLightning/pytorch-lightning/blob/69575204f23f8fb3bc4597c1766bbc9593dc8acb/pytorch_lightning/loggers/wandb.py#L136
which comes from the wrong `wandb` init
https://github.com/PyTorchLightning/pytorch-lightning/blob/69575204f23f8fb3bc4597c1766bbc9593dc8acb/pytorch_lightning/loggers/wandb.py#L112
Do you have a minimal example which we can add among tests?

**Comment by sshleifer** [comment]
Unfortunately I do not, the problem was encountered with
```python
Trainer(distributed_backend="ddp",  logger=WandbLogger(name='hello'))
```
So if you put that wherever you guys test ddp, it should suffice.

**Comment by awaelchli** [comment]
I will try to write a test that (ideally for all loggers) makes sure the logger is only used in rank 0 process, therefore not creating any files on rank > 0 and then I can also make sure these NoneTypeErrors don't happen on rank > 0.
