### ISSUE TITLE
multiprocessing cpu only training

### ISSUE THREAD

**Issue by artemru** [PyTorchLightning/pytorch-lightning#222]
I would like to know if it's possible to train a model with multiprocess parallelism (no GPU available) using Lightning (sync analogue of https://pytorch.org/docs/stable/notes/multiprocessing.html#hogwild) ? After a quick glance, I've the impression that in `Trainer` all available options for parallelism are GPU based (if I'm not mistaken `torch.DPD` supports multiproc CPU-only training).

**Comment by Borda** [comment]
@artemru @neggert are you interested in sending a PR? :robot:

**Comment by skepticleo** [comment]
I would like to take this up.

**Comment by Borda** [comment]
Cool! Thx @skepticleo

**Comment by awaelchli** [comment]
Looks like this was recently added #1158 :)

**Comment by miguelalonsojr** [comment]
Reopening for further discussion: after digging through the codebase, https://github.com/PyTorchLightning/pytorch-lightning/pull/1158 doesn't seem to actually speed things up on a single node the way that pytorch hogwild (https://pytorch.org/docs/stable/notes/multiprocessing.html#hogwild) does. In order to use hogwild in pytorch, the model must be shared across each process through share_memory(), which is never called in PL.
