### ISSUE TITLE
when no checkpoints are saved, test fails

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#2238]
Build a model that doesn't save a checkpoint and this crashes.
It should use the last model instead.
```
model = ...
trainer = Trainer(fast_dev_run)
trainer.fit(model)
trainer.test()
```

@yukw777 
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <torch.serialization._open_file object at 0x7f443d4d88d0>, name = ''
mode = 'rb'

    def __init__(self, name, mode):
>       super(_open_file, self).__init__(open(name, mode))
E       FileNotFoundError: [Errno 2] No such file or directory: ''
```

The test for this should be:

```
def test_no_ckpt_test(tmpdir):
    model = EvaluationModel()
    trainer = Trainer(fast_dev_run)
    trainer.fit(model)
    trainer.test()
```

**Comment by yukw777** [comment]
oops, i'll send out a fix soon!

**Comment by nischal-sanil** [comment]
Hi,

I am currently facing this issue, is there any work around that I could do to resolve this?

**Comment by williamFalcon** [comment]
```    trainer.test(model)```

**Comment by yukw777** [comment]
@nischal-sanil could you help me understand the issue better by explaining how you don’t have any models saved?

**Comment by nischal-sanil** [comment]
I was running the Trainer with `fast_dev_run` set to True, hence there were no checkpoints. Changing  `trainer.test()` to `trainer.test(model)` has resolved the issue.
Thanks,

**Comment by nischal-sanil** [comment]
Hi again,

Consider the following code snippet

```
class Net(LightningModule):
    ...

resnet18 = models.resnet18(pretrained=True)
model = Net(resnet18)

# parameters before training
old_params = model.parameters()

trainer = Trainer(max_steps=10) 
trainer.fit(model)  

# parameters after training 
new_params = model.parameters()
```

Where I store the parameters of the model before and after training in `old_params` and `new_params`, a check on their equality returns `True`, suggesting there're no changes to the parameters.

```
def check_params(old,new):
    return all([torch.equal(o,n) for o,n in zip(old,new)])

check_params(old_params,new_params)
## True
```
 Therefore, while running `trainer.test(model)` the trained model is not used for testing. And I am not able to figure out if this is an expected behavior of the model or there is a problem with my class definition.

**Comment by yukw777** [comment]
@williamFalcon is it true that if `fast_dev_run` is `True`, there is no checkpoints saved? I just tried to manually check this in `test_test_checkpoint_path`, but `checkpoint_callback` of the trainer still had a valid `best_model_path` even when `fast_dev_run` is `True`.

@nischal-sanil your code comparing the old parameters to the new parameters is not quite correct. Since the tensors returned by `model.parameters()` are "references" to the underlying data, both `old_params` and `new_params` would point to the same "trained" tensors, hence `check_params()` would return `True`. You'd have to do something like `old_params = [p.clone() for p in model.parameters()]` to get around that.

**Comment by williamFalcon** [comment]
fast_dev_run should not save checkpoints (nor write a logs file). it's like a "compiler"

**Comment by yukw777** [comment]
@williamFalcon hmm maybe there's a bug? I see this:

```
❯ python pl_examples/basic_examples/cpu_template.py --fast_dev_run True
/Users/peteryu/.pyenv/versions/pl/lib/python3.7/site-packages/graphql/type/directives.py:55: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  assert isinstance(locations, collections.Iterable), 'Must provide locations for directive.'
Running in fast_dev_run mode: will run a full train, val and test loop using a single batch
GPU available: False, used: False
TPU available: False, using: 0 TPU cores

  | Name      | Type        | Params | In sizes   | Out sizes 
--------------------------------------------------------------------
0 | c_d1      | Linear      | 39 M   | [2, 784]   | [2, 50000]
1 | c_d1_bn   | BatchNorm1d | 100 K  | [2, 50000] | [2, 50000]
2 | c_d1_drop | Dropout     | 0      | [2, 50000] | [2, 50000]
3 | c_d2      | Linear      | 500 K  | [2, 50000] | [2, 10]   
Epoch 1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.18it/s, loss=2.523, v_num=0]
❯ ls lightning_logs/version_0/checkpoints/epoch=0.ckpt 
lightning_logs/version_0/checkpoints/epoch=0.ckpt
```

**Comment by williamFalcon** [comment]
added a warning and return {}
