### ISSUE TITLE
Stop at Validation sanity check

### ISSUE THREAD

**Issue by hminle** [PyTorchLightning/pytorch-lightning#2295]
Hi,

My code stops at Validation sanity check, there is no error, just stop right there
![image](https://user-images.githubusercontent.com/16201681/85189168-30a38b00-b27a-11ea-8ce6-81ad1296ba0d.png)

How should I fix this issue?

#### What have you tried?
I tried to build a dummy valid dataloader, and it works okay. But if I pass a real validation image set, it stops at sanity check.

#### What's your environment?

 - OS: Linux. I check with both GPU and CPU but still fail
 - Packaging conda
 - Version latest

Thanks

**Comment by PC09** [comment]
hi, how did you solve this? I'm facing the same issue

**Comment by hminle** [comment]
> hi, how did you solve this? I'm facing the same issue

Hi @PC09 , I find neither any error nor reasons leading to this issue.
I cannot say it clearly a bug or not. 
I overcome this issue by setting `trainer = Trainer(num_sanity_val_steps=0)`
Hope this help you

**Comment by akalieren** [comment]
It is not bug, validation sanity is used for checking whether there is an error or not in validation step before iterating a training epoch. 

For the people who encounter this issue, setting `num_sanity_val_steps` as 0 is not solution since stopping in sanity check indicating there is an erorr in your validation step.

**Comment by AnkushMalaker** [comment]
I'm also encountering the same issue. The sanity check should exit out or report issues if the check fails. Disabling isn't a solution as mentioned by @alierenak . This issue should be reopened IMO, @hminle .

**Comment by hminle** [comment]
Hi @AnkushMalaker, could you open a new issue with your detail description? I may also learn about it.

**Comment by AnkushMalaker** [comment]
@hminle I was mistaken. The sanity check isn't the issue, the model isn't completing a forward pass itself on TPU. I found this by disabling the sanity check and running a pass. The issue must be somewhere else, I will check if there's a bug in my code and then open an issue accordingly.

**Comment by erayerturk97** [comment]
If anyone is having a similar issue, it may be related to a synchronization issue across multiple gpus/tpus. I had this issue due to the way that I was logging my metrics: inside the compute function, I was checking if the metrics were updated to disable warnings, and the `update_called` flag was not synced across GPUs, resulting in a hang after validation sanity check.

**Comment by tccgogogo** [comment]
> 如果有人遇到类似的问题，则可能与多个 gpu/tpu 之间的同步问题有关。我遇到此问题是由于我记录指标的方式：在计算函数中，我检查指标是否已更新以禁用警告，并且该`update_called`标志未在 GPU 之间同步，导致验证健全性检查后挂起。

请问怎么解决的，我也一直卡死在了Sanity Checking DataLoader 0:   0%|
