### ISSUE TITLE
validating  test steps before start of testing

### ISSUE THREAD

**Issue by Nilanshrajput** [PyTorchLightning/pytorch-lightning#2906]
## 🚀 Feature
Do validation of complete test step with one batch to verify no error are present just as we do while at start of training

**Comment by rohitgr7** [comment]
Doesn't `fast_dev_run` do it for test batch as well?
https://github.com/PyTorchLightning/pytorch-lightning/blob/28f79d9f7ad7a249c7cbde2b98d6cb38fb4d755a/pytorch_lightning/trainer/trainer.py#L480-L489

**Comment by Nilanshrajput** [comment]
@rohitgr7 at the start of training validation steps takes places so something similar at the start of testing, I should change the title i think

**Comment by rohitgr7** [comment]
I think you are taking about validation sanity check.

**Comment by Nilanshrajput** [comment]
yup you are right but it will be a good idea to have similar test_sanity_check

**Comment by awaelchli** [comment]
@rohitgr7 is right, fast_dev_run does that. There is however as mall difference to the sanity val steps

- num_sanity_val_steps is automatically on (default 5) while fast_dev_run is a manual switch (default False)
- sanity check is automatic on because most users have their validation at the end of epoch and it can take a long time until you arrive there and have an error show up
- fast_dev_run is more for the case when you already know you have a bug and you want to easily debug with one batch, so you switch it on

Introducing a new argument num_sanity_test_steps, we would have to decide:
- run the test sanity check only in fit
- run the test sanity check only in test
- run the sanity check in both fit and test

First option is not very clean because we don't know if user will call test after fit, so running the sanity check could be a "waste". 
Second option is also not very clean because if user runs .fit() before .test() what's the point. These are my thoughts.
