### ISSUE TITLE
How to use multiple metric monitors in ModelCheckpoint callback?

### ISSUE THREAD

**Issue by angshine** [PyTorchLightning/pytorch-lightning#2908]
#### What is your question?
How can I use multiple metric monitors in the `ModelCheckpoint`？ In another way, how can I use multiple `ModelCheckpoint` callbacks？It seems that the `Trainer` only accepts a single`ModelCheckpoint` in the `checkpoint_callback` argument.

#### Code
```shell
site-packages/pytorch_lightning/trainer/callback_config.py", line 46, in configure_checkpoint_callback
    checkpoint_callback.save_function = self.save_checkpoint
AttributeError: 'list' object has no attribute 'save_function'
```
#### What's your environment?

 - OS: Ubuntu 16.04
 - Packaging: pip
 - Version: pytorch-lightning==0.9.0rc12

**Comment by awaelchli** [comment]
We currently don't support multiple ModelCheckpoint callbacks. 
For monitoring multiple metrics with the same callback, I think you have to use the Results object:
https://pytorch-lightning.readthedocs.io/en/latest/results.html#trainresult

**Comment by carmocca** [comment]
Do you plan to support it? It would be nice to be able to do the following:
```python
on_best_precision = pytorch_lightning.callbacks.ModelCheckpoint(
    filepath=filepath + "epoch={epoch}_precision={precision}",
    monitor="precision",
    save_last=True,
    save_top_k=3,
    mode="max",
)
on_best_recall = pytorch_lightning.callbacks.ModelCheckpoint(
    filepath=filepath + "epoch={epoch}_recall={recall}",
    monitor="recall",
    save_last=True,
    save_top_k=3,
    mode="max",
)
every_five_epochs = pytorch_lightning.callbacks.ModelCheckpoint(
    filepath=filepath + "epoch={}",
    period=5,
    save_top_k=-1,
)
trainer = pl.Trainer(
    checkpoint_callback=[on_best_precision, on_best_recall, every_five_epochs],
)
```
and something similar for the `early_stop_callback` flag.

**Comment by carmocca** [comment]
ping @awaelchli

**Comment by awaelchli** [comment]
I think yes, one day we will manage that. However, there are soooo many edge cases we need to consider, and we haven't even figured out all of them for the case of a single checkpoint callback. We need to approach this with care. It should be done by someone who is very confident with how model checkpointing works in PL (solely my opinion of course, not saying you or anybody else can't do it, it's just generally a hard task in my opinion, because it connects to many parts of the trainer, e.g. **validation, early stopping, resuming from checkpoints, formatting names for checkpoint files, topk management, saving the last, persisting state**, ... the list goes on). 

cc @PyTorchLightning/core-contributors

**Comment by bartmch** [comment]
Hi, this would be a great addition to Lightning! Do you know roughly when you're planning to include this feature?

**Comment by awaelchli** [comment]
@bartmch You can pass in multiple callbacks to the Trainer, just make sure you have the filename set properly in the checkpoint callback so that the checkpoints don't collide.

**Comment by kapsner** [comment]
Any update on this? Is this working? I am trying to log loss and accuracy using 2 ModelCheckpoints, however, with regards to the model checkpoint filenames, logging for accuracy seems not to work as it says always "0.00" for the "best" value.

**Comment by awaelchli** [comment]
did you set max for the mode with accuracy? I suppose with mode=min, 0 accuracy would be the best.

**Comment by kapsner** [comment]
Yes, mode is 'max'. So monitoring 2 metrics using 2 ModelCheckpoints should work now?

**Comment by awaelchli** [comment]
I'm not sure if we have specific tests for that but it should, yes. 
Important is to set the filename correctly so that the files always have different names. So I recommend to include the monitor key in the filename.

**Comment by carmocca** [comment]
We don’t. We are still limited by the fact that we save callbacks by their type, thus overwritting any with the same type

**Comment by ananthsub** [comment]
@carmocca this will come up with #6146 with this scenario:

- A user has a large training data set and wants to periodically checkpoint during the training epoch. They don't care about the monitor value or top K models here, but they want to save a checkpoint that they can resume from
- The user wants to track a monitor value during validation in order to keep track of the top k models. This currently isn't handled in #6146 since we'd need support for multiple monitors and to know which phase (training, validation) they apply. The other solution would be to create 2 checkpoint callbacks (1 for training, 1 for validation), but then we'll run into how callback state is serialized into the checkpoint dict. 

@awaelchli  @carmocca how should we proceed?

**Comment by carmocca** [comment]
I personally would go for solving:

> but then we'll run into how callback state is serialized into the checkpoint dict

**Comment by ananthsub** [comment]
@carmocca I agree, this feels like an important and general addition. open to suggestions in #6467

**Comment by awaelchli** [comment]
Me too, I also think that having multiple instances of model checkpoint is better than supporting multiple monitor values in the same. 

> We don’t. We are still limited by the fact that we save callbacks by their type, thus overwritting any with the same type

Yes it's true for loading but just saving the checkpoints with multiple instances should work today?

My suggestion is to use an identifier for each callback instance and derive a unique key when saving. This would allow us to restore from a checkpoint even if the user has changed the callback list.

In ModelCheckpoint, the unique identifier could be derived from the monitor key automatically. Same for early stopping and other callbacks that safe state.

**Comment by kapsner** [comment]
> Important is to set the filename correctly so that the files always have different names. So I recommend to include the monitor key in the filename.

Thanks - I checked again and recognized a typo in the metric key in the file name - now it's working!

However, I don't see an issue with ModelCheckpoints being overwritten currently... My setup is as follows and working for me:

```python
# define ModelCheckpoint callbacks
model_checkpoint_cb_loss = ModelCheckpoint(
    monitor="loss/valid",
    verbose=False,
    save_last=True,
    save_top_k=3,
    save_weights_only=False,
    mode='min',
    period=1,
    dirpath=None,
    filename="{epoch}-{loss/valid:.2f}"
)
model_checkpoint_cb_acc = ModelCheckpoint(
    monitor="auroc/valid",
    verbose=False,
    save_last=True,
    save_top_k=3,
    save_weights_only=False,
    mode='max',
    period=1,
    dirpath=None,
    filename="{epoch}-{auroc/valid:.2f}"
)
```

Those callbacks are then passed to `trainer`.

For testing both metrics, I do:

```python
# fit the model
trainer.fit(model=model, datamodule=dm)

# Test multiple "best" checkpoints
for _ckpt in range(len(trainer.checkpoint_callbacks)):
    logging.info("Testing: monitor metric: {}".format(
        trainer.checkpoint_callbacks[_ckpt].monitor
    ))
    ckpt_path = trainer.checkpoint_callbacks[_ckpt].best_model_path
    logging.info("Best checkpoint path: {}".format(ckpt_path))

    # test the model using current checkpoint
    trainer.test(ckpt_path=ckpt_path)
```

**Comment by awaelchli** [comment]
That's great!

> However, I don't see an issue with ModelCheckpoints being overwritten currently...

Yes, the checkpoint files get written and that's all fine, and it saves all the model weights and hyperparameters. Most users will be happy with that. However, one additional thing we save into the checkpoint dictionary is the state of all callbacks that you've used, even the ModelCheckpoint itself. So these are unfortunately not saved correctly, and you will only run into problems if you try to do `Trainer(resume_from_checkpoint=...)`. If you would do that, and run your for loop above again, you would see the same values twice, because one of them got overwritten by the other.
