### ISSUE TITLE
Log epoch as step when on_epoch=True and on_step=False

### ISSUE THREAD

**Issue by ToucheSir** [PyTorchLightning/pytorch-lightning#3228]
## 🚀 Feature

When using the new structured `Result` API, it is no longer possible to force PL to report the epoch as the current step to loggers instead of the global step (or elapsed number of training steps).

### Motivation

 This results in confusing results when viewing results in a tool that uses step count by default (e.g. tensorboard's scalars view). Intuitively, one would think `.log(..., on_epoch=True, on_step=False)` would count epochs and not steps.

It is possible to obtain this behaviour by overriding both `training_epoch_end` _and_ `validation_epoch_end` and returning an `EvalResult` with a "step" metric. Unfortunately, this adds back a bunch of boilerplate and many of the nice metric aggregation features PL offers when `*_epoch_end` is not implemented.

### Pitch

Either a) allow for overriding the step for a given result, or b) default that step to `current_epoch` when `on_epoch=True` and `on_step=False`.

### Alternatives

1. Use a "step" key with the old dict-based logging system (not documented, but worked as of 0.8.3)
2. Override train/validation_epoch_end and add return an `EvalResult` with `.log('step', self.current_epoch)`.

### Additional context

Original discussion: https://forums.pytorchlightning.ai/t/is-there-a-way-to-only-log-on-epoch-end-using-the-new-result-apis/74/3

**Comment by s-rog** [comment]
any ideas for the case on_epoch=True and on_step=True?

**Comment by williamFalcon** [comment]
is this behavior really desired? When graphing, don't you want everything to be on the same scale?
if this change happens, the metrics logged by epoch won't be able to be compared visually with things logged per step...

makes it really hard to compare apples to apples.

I don't think we should make this change.
@PyTorchLightning/core-contributors ?

**Comment by ToucheSir** [comment]
As per the discourse discussion, logs could be on epoch only xor step only so everything would be on the same scale (modulo whatever ephemeral logs show up on the progress bar). However, it's not possible now if one wants to log _everything_ on epoch without [overriding `*_epoch_end`](https://forums.pytorchlightning.ai/t/is-there-a-way-to-only-log-on-epoch-end-using-the-new-result-apis/74/8).

**Comment by edenlightning** [comment]
This changed with[ new API for logging](https://pytorch-lightning.readthedocs.io/en/stable/logging.html). Please upgrade to 1.0.2. Feel free to reopen if needed.

**Comment by johschmidt42** [comment]
Is this problem solved now? Or did you decided that this behavior is generally not desired? When I look at the created graphs, e.g. loss per epoch, I still see the steps on the x-axis instead of the epochs. And I can't find anything in the logging API to change this behavior. This makes is hard to identify the number of epochs for a certain experiment, just by looking at the epochs graph. When I use manual logging, I get the desired result, but the metrics do not show up in trainer.logged_metrics, which I think is required e.g. for the ModelCheckpoint callback.

**Comment by johschmidt42** [comment]
Also, it would be really nice if one could specify the suffix when using log(... , on_step=True, on_epoch=True).

**Comment by keunwoochoi** [comment]
hm, honestly, the log api with `on_step` and `on_epoch` is extremely confusing to me.

**Comment by s-rog** [comment]
The conclusion we came to was that this is not desired behavior, and the custom suffixes can possibly be added in a future PR.

If you've got questions feel free to hop in discussions or slack!

**Comment by pederismo** [comment]
I'm doing distributed training, therefore I really appreciate the sync_dist flag in self.log, but I would also like to plot on_epoch with the epochs as x-axis. I think it would be a really cool feature, as manual logging doesn't have sync_dist and many people have requested it!

**Comment by mpds** [comment]
I see some cases where this might be desired behavior. First, when I log `val_loss` like this:
```python
def validation_step(self, batch, batch_idx):
    ...
    self.log("val_loss", loss, on_step=False, on_epoch=True)
```
It doesn't make sense to me to show steps on the x-axis. 

Second, sometimes I want to compare the difference between running the same model with a larger dataset but using the same number of epochs. Because it's logging steps on the x-axis, I can't properly compare them, since a larger dataset produces more steps (even with the same number of epochs).

**Comment by phisad** [comment]
Still need to add `"step": self.current_epoch` otherwise epoch does not show up for validation metrics.

```
self.log_dict({"val/acc/total": accuracy_total, "step": self.current_epoch + 1})
```

**Comment by rabyj** [comment]
I agree with @mpds, I recently transferred from TensorFlow2 with Keras  which also values high level abstraction, and it was pretty easy to log all scalar metrics per epoch or per step.

Having always worked with epochs logging, because the batch size (and so number of steps) varied in my trainings, the default "x-axis = step" when specifying `on_step=False, on_epoch=True` was jarring.

**Comment by noamzilo** [comment]
Is there a full, small, runnable example of this?

I just want to see how to rig everything together to make it happen, which is not clear from the discussions alone

**Comment by rabyj** [comment]
@noamzilo personally, I put the metric logging into the training and validation steps end, and used log_dict. [This model](https://github.com/rabyj/epi_ml/blob/rabyj/epi_ml/python/core/model_pytorch.py) might answer some of your questions and clarify how this all fits together. If I don't specify the step, the resultings graphs have a "step" x-axis instead of epoch.

**Comment by rohitgr7** [comment]
I'd recommend using an advanced logger (like wandb) to configure this on the UI itself since step is logged by default with all the metrics, we log epoch as well with step so you can create a new graph with x-axis as epoch and y-axis as your metric.

**Comment by martinferianc** [comment]
I have spent several hours to debug this and it is extremely disappointing how the documentation in this very crucial part of almost machine learning project is misleading and lacking. I ended up doing the logging and tracking manually.

**Comment by awaelchli** [comment]
@martinferianc I'm sorry. If you could give us some details about where you struggled to understand the logging or where you looked, then this can be improved in the future. We are always happy about this kind of feedback.

**Comment by JohnKilbride** [comment]
It would be really nice for this functionality to be added. 

If I have two models, one with a batch of 16 and one with a batch of 2048, and I'm looking at the per-epoch-loss why would I want the dots to be rendered a zillion miles away on the graph? It prevents visual comparison. 

I would expect setting on_step=True and on_epoch=True to log RMSE (for examples) to log metrics per-epoch AND per-step. 

I don't think using W&B is a viable option either. That logger has numerous documented issues and I've been forced to stop using it in the past due to issues with gradient accumulation and running it with distributed processing.

**Comment by martinferianc** [comment]
Dear @awaelchli, after rereading my comment, I would like to apologise for the harshness of my critique, but I was very frustrated about this and @JohnKilbride perfectly summarised the issue.

**Comment by anishchhaparwal** [comment]
I second @martinferianc, the user should have the option of logging: per-epoch or per step or both.
The user should decide how to use the tool not the other way around.

**Comment by zhiqiangw** [comment]
Dear @awaelchli, I totally agree with @JohnKilbride. I have spent several hours debugging and searching for this. It is very frustrating that pytorch lightning does not support this functionality.
Recently, I am switching to pytorch lightning. Before using pytorch lightning, I directly use tensorboard for logging. I have some experiments logging with tensorboard where the x-axis of validation is `epoch`. Now, I am using pytorch lightning where the x-axis is `step`. I cannot compare the new experiments with my previous experiments.

**Comment by Borda** [comment]
> I would expect setting on_step=True and on_epoch=True to log RMSE (for examples) to log metrics per-epoch AND per-step.

well, that would be my expectation too :otter:

**Comment by hardianlawi** [comment]
I would also like to have this feature. Currently, the approach proposed by @phisad works for me

**Comment by thefiddler** [comment]
Same issue here, after several hours I still haven't found out how to log epochs on the x-axis correctly. This is not documented anywhere in the api docs afaict.

**Comment by emilaz** [comment]
Using `self.log_dict({"val/acc/total": accuracy_total, "step": self.current_epoch + 1})`  leads to the followig warning for me.

` UserWarning: You called `self.log('step', ...)` in your `on_validation_epoch_end` but the value needs to be floating point. Converting it to torch.float32.`

Can we please just natively have the epoch on the x-axis when `on_step=False, on_epoch=True`?

**Comment by ofarajun** [comment]
Will this be changed in a future release?  Would really like a way to have epochs on the x-axis when on_epoch=True and on_step=False.

**Comment by michal-choinski** [comment]
Same here, it's not possible to compare experiments between each other (Tensorflow vs Pytorch, or across different batch sizes). Really disappointing that this feature is not supported by PL

**Comment by michal-choinski** [comment]
I already spent 2 days trying to solve the problem of logging epochs instead of steps. I was trying to apply the trick mentioned above that logs step as a metric. Then the first epoch is logged correctly, but unfortunately the second fails with the following error (I am using Mlflow):

File "/workspace/ai-tools/src/pytorch/train_utils/experiment/experiment.py", line 221, in _train
    trainer.fit(
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 248, in on_advance_end
    self.val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/evaluation_loop.py", line 255, in on_run_end
    self.trainer._logger_connector.log_eval_end_metrics(all_logged_outputs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py", line 141, in log_eval_end_metrics
    self.log_metrics(metrics)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/logger_connector.py", line 108, in log_metrics
    logger.log_metrics(metrics=scalar_metrics, step=step)
  File "/usr/local/lib/python3.8/dist-packages/lightning_utilities/core/rank_zero.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loggers/mlflow.py", line 272, in log_metrics
    self.experiment.log_batch(run_id=self.run_id, metrics=metrics_list)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/client.py", line 918, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/client.py", line 320, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/rest_store.py", line 303, in log_batch
    metric_protos = [metric.to_proto() for metric in metrics]
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/tracking/rest_store.py", line 303, in <listcomp>
    metric_protos = [metric.to_proto() for metric in metrics]
  File "/usr/local/lib/python3.8/dist-packages/mlflow/entities/metric.py", line 41, in to_proto
    metric.step = self.step
TypeError: 1.0 has type float, but expected one of: int

Does anyone have a working solution for this, or is switching to a different library simply necessary? It would be a shame as I already invested quite a lot of time to implement a new pipeline with PL.

**Comment by michal-choinski** [comment]
For those who are struggling with the same issue, the solution that worked for me is:
- add step (`step = self.current_epoch`) as a metric
- re-implement a MlflowLogger with a little change: `if step is not None`, always cast it to int

**Comment by Shivin302** [comment]
Very annoying issue that still persists almost 4 years later. I had to use
[https://github.com/Lightning-AI/pytorch-lightning/issues/2110#issuecomment-1114097730](this solution) as a workaround

**Comment by elidub** [comment]
For anyone using WandB looking for a solution: 

Change the _X axis options_ to display _epoch_ instead of _step_.

<img width="374" alt="image" src="https://github.com/user-attachments/assets/6e62abd5-8470-4e5d-842e-99ed983be1a3">

**Comment by crlandsc** [comment]
For anyone still running into this issue, I found a useable workaround here: https://github.com/Lightning-AI/pytorch-lightning/issues/2110#issuecomment-1114097730

There is one small fix, make sure that **`on_training_epoch_end`** is actually **`on_train_epoch_end`** (as shown below):

> I create a simple callback `OverrideEpochStepCallback` which overrides the `step` to the current epoch index. `step` is overridden on every _epoch-ending_ procedure:
> 
> ```python
> from pytorch_lightning.callbacks import Callback
> import pytorch_lightning as pl
> 
> class OverrideEpochStepCallback(Callback):
>     def __init__(self) -> None:
>         super().__init__()
> 
>     def on_train_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule):
>         self._log_step_as_current_epoch(trainer, pl_module)
> 
>     def on_test_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule):
>         self._log_step_as_current_epoch(trainer, pl_module)
> 
>     def on_validation_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule):
>         self._log_step_as_current_epoch(trainer, pl_module)
> 
>     def _log_step_as_current_epoch(self, trainer: pl.Trainer, pl_module: pl.LightningModule):
>         pl_module.log("step", trainer.current_epoch)
> 
> trainer = pl.Trainer(callbacks=[OverrideEpochStepCallback()])
> ```
> 
> This way, you don't need to implement `training_epoch_end`. `training_step` can log metrics every epoch and the `OverrideEpochStepCallback` takes care of the step number:
> 
> ```python
> def training_step(self, batch, batch_idx):
>         x, y = batch
>         y_pred = self(x)
> 
>         loss = F.cross_entropy(y_pred, y)
>         acc = multi_acc(y_pred, y)
> 
>         data_dict = {
>             "loss": loss,  # the 'loss' key needs to be present
>             "train/loss": loss,
>             "train/acc": acc,
>         }
>         log_dict = data_dict.copy() # we don't want to log `loss` metric
>         log_dict.pop("loss", None)
>         self.log_dict(log_dict, on_step=True, on_epoch=True, logger=True, prog_bar=True) # step and epoch logs both work!
>         return data_dict
> ```

**Comment by simonebonato** [comment]
https://github.com/Lightning-AI/pytorch-lightning/issues/3228#issuecomment-2450387419

Thanks for the Callback! works wonderfully!

Still a pity this is not the default behaviour yet...
