### ISSUE TITLE
'precision=16' doesn't change GPU memory consumption

### ISSUE THREAD

**Issue by najeeb95** [PyTorchLightning/pytorch-lightning#3382]
Hello, 
I'm trying to do FP16 training by enabling 'precision=16' but it doesn't seem to reduce my GPU memory consumption, which is my main goal.

The code I ran was from this article: 
https://towardsdatascience.com/from-pytorch-to-pytorch-lightning-a-gentle-introduction-b371b7caaf09

All I did was change the parameter 'precision' to 16/32 to see if there's any difference in memory. I checked the memory consumption via 'nvidia-smi' and there was no difference at all.

I also tried it on a model I have which is a fully connected neural network that takes about 9GB with regular FP32 training and there's no improvement in 'precision=16' (in some cases the memory even increased in FP16 compared to FP32).

I have pytorch 1.6 with native amp. RTX 2080 Ti GPU. 

Thanks.

**Comment by tsteffek** [comment]
As a random citizen that delved into such matters lately, I see two possible issues:
- Following [this reply](https://discuss.pytorch.org/t/what-does-pytorch-do-when-calling-tensor-half/58597/5?u=tsteffek) (Nov '19) from PyTorch folk: 
  > If you are checking the used memory via nvidia-smi, note that you might see the cached memory as well. 
  torch.cuda.memory_allocated() might give you a better number.
- 16-bit precision utilizes [PyTorch's Autocast](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.autocast) instead of actual 16-bit precision.  Have a look at [this list](https://pytorch.org/docs/stable/amp.html#op-specific-behavior) to see what ops use what precision.
  Depending on your model's sizes and ops, this might impact the size reduction you experience.
