### ISSUE TITLE
Broken links in README.md.

### ISSUE THREAD

**Issue by ninfueng** [PyTorchLightning/pytorch-lightning#3931]
## 📚 Documentation

Hello,
There are broken links in `README.md` on  [Dueling-DQN and Reinforce](https://github.com/PyTorchLightning/pytorch-lightning/blame/9c415d2c71ddc44ca3344ba1136c0dd546fc5ef6/README.md#L237-L238) sections.

**Comment by Borda** [comment]
@ninfueng nice, mind send a quick PR?

**Comment by pbmstrk** [comment]
Jumping in because I noticed that the DQN link (listed under Examples) in the pytorch-lightning docs is also broken. They all point to `https://pytorch-lightning-bolts.readthedocs.io/en/latest/reinforce_learn.html`. From PyTorchLightning/pytorch-lightning-bolts#192 it seems that links are broken because RL was temporarily removed from master. When building the bolts docs from the master_RL branch the links all work. Not sure where they should point to until RL is added back?

**Comment by ninfueng** [comment]
@Borda I do not mind but somehow the links are working again. Maybe I should close this issue?

**Comment by Borda** [comment]
then all goos lol :] anyway thx for your report... 🐰
