### ISSUE TITLE
Add Aim logger

### ISSUE THREAD

**Issue by gorarakelyan** [PyTorchLightning/pytorch-lightning#3985]
## 🚀 Feature

Implement AimLogger to integrate with Aim.

### Motivation

Gor from Aim here. I am helping build [Aim](https://github.com/aimhubio/aim) – an open source project that helps to easily track and explore 100s of AI experiments in minutes. I figured it would be good for both parties to integrate Aim with PL. 

### Solution/Pitch

It appears the following needs to be done:
 - Implement AimLogger [here](https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pytorch_lightning/loggers)
 - Add tests [here](https://github.com/PyTorchLightning/pytorch-lightning/tree/master/tests/loggers)
 - Write documentation [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/loggers.rst)

 I will prepare a PR with said integration and I only want folks to review/merge it.

### Additional context

![aim-screen](https://user-images.githubusercontent.com/13848158/95452541-721b8b80-097a-11eb-99c6-0344a03797a7.png)

**Comment by edenlightning** [comment]
This project looks awesome!!
And the way you currently implemented lightning integration is great. We are currently not adding any built-in integration directly to the lightning repo due to very high maintenance costs that come along with it. 

Let us know if there's any other way we can help, such a great tool!
