### ISSUE TITLE
[FEATURE] Integrate Captum Interpretability as Callback.

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#4257]
### Motivation

Here is a Captum example: https://captum.ai/tutorials/Resnet_TorchVision_Interpret

```
Example: callback = CallbackInterpretability(algorithm="integrated_gradients", backend="captum", frequency=5, grid_size=5). And it would create this kind of images every 5 epochs for grid_size * grid_size images.
```

**Comment by addisonklinke** [comment]
@tchaton I see you marked this as completed, but there isn't a PR link and I don't see anything that looks related in the [latest callbacks folder](https://github.com/Lightning-AI/pytorch-lightning/tree/master/src/lightning/pytorch/callbacks). Did you run into any blockers or this just wasn't prioritized?

I've got this prototype
```python
from typing import Optional, Any, Type

from captum.attr import Attribution, IntegratedGradients
import pytorch_lightning as pl
from pytorch_lightning.callbacks import Callback
from pytorch_lightning.utilities import rank_zero_only
from pytorch_lightning.utilities.types import STEP_OUTPUT
import torch

from my_internal_lib import BaseRankingModel


class ModelInterpretabilityCallback(Callback):

    def __init__(self, attributor_cls: Type[Attribution] = IntegratedGradients) -> None:
        super().__init__()
        self.attributor_cls = attributor_cls
        self._attributor: Optional[Attribution] = None
        self._attributions = []

    @property
    def attributor(self) -> Attribution:
        if self._attributor is None:
            raise RuntimeError(
                "Attributor has not been initialised yet. "
                "Did you try to access it before `on_test_start` was called?"
            )
        return self._attributor

    def on_test_start(self, trainer: pl.Trainer, pl_module: pl.LightningModule) -> None:
        """Wrap forward method of model"""
        if not isinstance(pl_module, BaseRankingModel):
            raise ValueError("ModelInterpretabilityCallback only supports BaseRankingModel")
        self._attributor = self.attributor_cls(pl_module.forward)

    def on_test_batch_end(
        self,
        trainer: pl.Trainer,
        pl_module: pl.LightningModule,
        outputs: STEP_OUTPUT,
        batch: Any,
        batch_idx: int,
        dataloader_idx: int = 0,
    ) -> None:
        """Compute attributions for the batch"""
        inputs = pl_module.get_forward_inputs(batch)

        # Lightning has gradients off during testing by default, but gradient-based attributors need them
        # Re-enable on this particular set of `inputs`
        # Use `detach` to avoid tracking history from previous operations 
        # while maintaining a view to avoid copies
        inputs = tuple(x.detach().requires_grad_(True) for x in inputs)
        with torch.set_grad_enabled(True):
            attributions = self.attributor.attribute(inputs)  # FIXME still RuntimeError :/
        self._attributions.append(attributions.cpu())
```

As you can see in `on_test_batch_end`, I'm trying (unsuccessfully) to avoid
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

I'm pretty sure my `torch.set_grad_enabled` has no effect because the `Trainer(inference_mode=True)` [default param](https://github.com/Lightning-AI/pytorch-lightning/blob/77f9811a776297c63823a32a3b310492ef3c798d/src/lightning/pytorch/trainer/trainer.py#L124) means the `@_no_grad_context` manager [decorating](https://github.com/Lightning-AI/pytorch-lightning/blob/77f9811a776297c63823a32a3b310492ef3c798d/src/lightning/pytorch/loops/evaluation_loop.py#L119-L120) `_EvaluationLoop.run()` will [select](https://github.com/Lightning-AI/pytorch-lightning/blob/77f9811a776297c63823a32a3b310492ef3c798d/src/lightning/pytorch/loops/utilities.py#L174-L175) `torch.inference_mode` which according to their [docs](https://docs.pytorch.org/docs/stable/generated/torch.autograd.grad_mode.inference_mode.html)

> unlike some other mechanisms that locally enable or disable grad, entering inference_mode also disables to [forward-mode AD](https://docs.pytorch.org/docs/stable/autograd.html#forward-mode-ad)

From what I can tell my options are

1. Adjust the callback hooks to run during training when `torch.inference_mode` is not activated by Lightning. This is undesirable because training samples are biased and I don't want to slow down the core training throughput (even if it is only sampling a subset of `batch_idx`)
2. Flip `Trainer.inference_mode` off before testing. First, this isn't exposed so I can't actually use this approach. Even if it was, it still is undesirable because other logic during `trainer.test()` (outside of the interpretability callback) might reasonably (yet wrongly) assume gradients are off
3. Change the initialization of my `Trainer` to `inference_mode=False`. This will incur a lot of unexpected behavior during the validation loop. I _only_ need gradients on temporarily for these forward passes during testing
4. Only support non-gradient based `Attribution` objects

Currently I think Lightning forces me into 4 which is unfortunate because I'd like to take advantage of gradient-based attribution methods

**Comment by AdamBajger** [comment]
From what I have seen in the current Captum implementation, it is not meant to accomodate nor take advantage of the lightning Trainer executioon loop and callbacks. To fully integrate, I would imagine the callback having applied hooks to store the gradients AND activations from the respective layer at the forward pass and have them retrieved in the callback on_batch_end() hook.
The downside is that if you would want to use, for example, LRP, you would have to modify the whole model before starting the whole process (LRP modifies the way backpropagation works) and that would inevitable break the selfcontainedness of the callback, which might not be desired.
