### ISSUE TITLE
Spec for DDP tests

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4397]

**Comment by edenlightning** [comment]
We can't run DDP right now on multiple GPUs. How can we run this with the current CI?

**Comment by edenlightning** [comment]
Can we do this without pytest? and collect results from process 0 or all of them?

**Comment by edenlightning** [comment]
Can we create global processes?

**Comment by awaelchli** [comment]
I'll give a short summary of what the challenge is and what we could explore (partially discussed already).

## How accelerator=ddp works

When we launch a ddp script like so:
```bash
python train.py --gpus 3 --accelerator ddp     <--- call this process 0
```

What happens under the hood is, process 0 will run on gpu 0 and launch two additional processes with these commands:

```bash
python train.py --gpus "1," --accelerator ddp   (+ some additional env variables)
python train.py --gpus "2," --accelerator ddp   (+ some additional env variables)
```

These three processes run independently until they finish training, then they terminate.

## How DDP testing currently works

It is basically non-existing. We have a handful of tests that simply launch a script and check if it finishes with exit code 0.
There is no additional unit testing done.

## How we expect DDP testing to work

In order to launch training as shown above, the test case(s) have to be in it's own script, say `test_train.py`.
Then, we want to run

```bash
pytest test_train.py --gpus 3 --accelerator ddp    <--- we need to enable these args somehow
```

Each subprocess should run the tests independently (there may be points where processes sync). 
At the end, we need to collect the pytest results from each subprocess. 

## Challenges

1. Launching processes as shown above can take 1-2 seconds.
2. Initialization of ddp connection in each subprocess adds additional overhead.
3. Trainer on rank 0 needs to initiate "pytest" launch command for children with the correct arguments
4. Handling multiple test cases in a single ddp script
5. Collecting the pytest results for failures and passed tests from each subprocess.


## Ideas how to address challenges

1) ?
2) Initialize ddp once and reuse connection for several test cases (this is similar to how we solved the "fit + test" ddp limitation). 
3) some Python magic
4) we may need to avoid prefixing functions with "test_" and call them manually in sequence. Need to study pytest magic.
5) ?

**Comment by awaelchli** [comment]
Which PR addressed the above points? The DDP launcher?
