### ISSUE TITLE
Does log_every_n_steps work in validation_step?

### ISSUE THREAD

**Issue by Maybewuss** [PyTorchLightning/pytorch-lightning#4527]
- I find that golbal_step is the training_step, if i want to log something every k validation_steps, how to implement？
- log_every_n_steps works in trains_loop but does not work in validation loop.
- Should add global_traing_step, global_val_step and global_test_step?
- self.log only support on_step and on epoch, can this api support k_steps or k_epoch (training, validation and test)?

**Comment by george-gca** [comment]
@Maybewuss  one thing you could do is use the [check_val_every_n_epoch](https://pytorch-lightning.readthedocs.io/en/latest/trainer.html#check-val-every-n-epoch) Trainer flag, so you do the validation every k training epochs. But if you would like to do the validation every time, but only log every k epochs, you could give the `k` value in the `__init__` of your model and store it in, for example, `self.log_every_k`. Then do in the `training_epoch_end` and in the `validation_epoch_end` something like `if self.current_epoch % self.log_every_k == 0:`.

If you want to do it for steps (batches) instead of epochs, do the same, but check the value in `training_step` and `validation_step`, maybe comparing it with the `batch_idx`.

**Comment by awaelchli** [comment]
PL supports it, but it is not meaningful to log metrics on step in validation. 
Maybe you are trying to log some images or other type of data samples?
In this case, you can do 


```python 
def validation_step(self, batch_idx, batch):

    if (batch_idx + 1) % self.trainer.log_every_n_steps: 
        self.logger.experiment.log_method(samples ... ) 
```

**Comment by Maybewuss** [comment]
> PL supports it, but it is not meaningful to log metrics on step in validation.
> Maybe you are trying to log some images or other type of data samples?
> In this case, you can do
> 
> ```python
> def validation_step(self, batch_idx, batch):
> 
>     if (batch_idx + 1) % self.trainer.log_every_n_steps: 
>         self.logger.experiment.log_method(samples ... ) 
> ```

Thanks
