### ISSUE TITLE
Create an Enum for tracking Train, validation, test stage 

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#4536]
### Motivation

The goal is to create single point of truth about stages for the trainer, so we don't get typo errors.

**Comment by Borda** [comment]
Similar to the trainer stage define TrainerPhase
https://github.com/PyTorchLightning/pytorch-lightning/blob/2d42ec008f7d6a653caa80f6ebd41171391d7bf3/pytorch_lightning/trainer/states.py#L22-L28

**Comment by Borda** [comment]
Let's do the same also for device type and distributed type...

**Comment by pquadri** [comment]
can i take this as first issue?

**Comment by Borda** [comment]
@pquadri sure, go ahead!

**Comment by pquadri** [comment]
i think someone already did this without closing the issue (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/states.py), i'll poke around and see if there are some strings running around rather than the Enum.
Also, `pytorch_lightning/utilities/enums.py` has a commit of a few days ago implementing the enums for device type and distributed type you mentioned
