### ISSUE TITLE
Make coverage great again

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#463]
I think it's time for some coverage clean up. We're sitting at around 93%. Let's bring it back up to 99% or perhaps *gasp 100%?

@Borda @neggert

**Comment by neggert** [comment]
Yeah, I've been thinking of doing some test cleanups that would hopefully make this easier. I mostly want to make better use of some of the convenience features that pytest provides. Off the top of my head:

* Use the [tmpdir fixture](http://doc.pytest.org/en/latest/tmpdir.html) for temporary directories, rather than moving things around manually with shutil
* Move some or all of the code in `pytorch_lightning.testing` into [test fixtures](https://docs.pytest.org/en/latest/fixture.html)
* Look at [parameterizing](https://docs.pytest.org/en/latest/fixture.html#parametrizing-fixtures) for cases where we have many tests with minimal changes, e.g. run a basic model on cpu, dp, ddp, ddp2.

These do have a little bit of cost by making the tests slightly more opaque, but IMO it would be worth it to get less overall code to maintain.

**Comment by Borda** [comment]
> * Use the [tmpdir fixture](http://doc.pytest.org/en/latest/tmpdir.html) for temporary directories, rather than moving things around manually with shutil
> * Move some or all of the code in `pytorch_lightning.testing` into [test fixtures](https://docs.pytest.org/en/latest/fixture.html)
> * Look at [parameterizing](https://docs.pytest.org/en/latest/fixture.html#parametrizing-fixtures) for cases where we have many tests with minimal changes, e.g. run a basic model on cpu, dp, ddp, ddp2.
* add/use [doctest](https://docs.python.org/2/library/doctest.html) which serves as a test and at the same time as examples, for instance, most of the examples in `numpy` or `sciki-learn` come from doctests...

I agree with you, and I would just each point make as a separate PR to kep it simple
