### ISSUE TITLE
Remove automatic reset after `compute()` in the Metric's API?

### ISSUE THREAD

**Issue by oterobaguer** [PyTorchLightning/pytorch-lightning#4641]
## 🚀 Feature
a) Remove automatic reset after `compute()` in the Metric API.
b) Option to automatic log running averages instead of batch-wise results

### Motivation

Some of the metrics normally used, such as 'Recall', 'Intersection over Union',... etc, make no sense if calculated for a small set of images. For example, in binary classification, a batch in which there is no positive case returns 0. However, running averages are much better in these cases. Lightning metrics are automatically reset after calling `compute()`. Why is this behavior? isn't  better to allow calling `compute()` many times, allowing for example, to compute running averages in between. If at some point a reset is needed the `reset()` method can always be called.

**Comment by SkafteNicki** [comment]
@oterobaguer currently the reset is called because processes are synced whenever `compute` is called. Since we sync by doing a `all_gather` operation by default, the metric states on all processes are being accumulated, which means that if we do not do `reset` in between calls to `compute` then we would basically end up accumulating metric states multiple times.

**Comment by SkafteNicki** [comment]
cc: @teddykoker 
Should we provide some way of computing running accumulated values?

**Comment by oterobaguer** [comment]
That would be great

**Comment by teddykoker** [comment]
Sorry I missed this. In hindsight i think it would make sense to not call `reset()` on `compute()` see comment here: https://github.com/PyTorchLightning/pytorch-lightning/pull/5193#issuecomment-755680377

**Comment by SkafteNicki** [comment]
Fixed by #5409. Closing now.
