### ISSUE TITLE
tensorboard two value every step

### ISSUE THREAD

**Issue by Limtle** [PyTorchLightning/pytorch-lightning#4692]
#### What is your question?
I have same question. Have any suggestion? thanks
#3997

**Comment by SkafteNicki** [comment]
@Limtle can you elaborate what your problem is?
Is it because you are seeing both a `train_loss:_step` and `train_loss:_epoch` curve?
Because then you just need to explicit set one of them to `False`:
`self.log('train_loss', loss, on_step=False, on_epoch=True)`
Please see the documentation: https://pytorch-lightning.readthedocs.io/en/latest/logging.html#automatic-logging

**Comment by Limtle** [comment]
Thanks. The code same as #3997. Then I find the same discussion in #4304
