### ISSUE TITLE
Potential bug in metric when updated with a slice of tensor in DDP

### ISSUE THREAD

**Issue by junwen-austin** [PyTorchLightning/pytorch-lightning#4781]
## 🐛 Bug

when a metric is updated with a slice of tensor as one of the inputs (either pred or target) with multiple GPU with DDP, it throws out an error:

```
RuntimeError: Tensors must be non-overlapping and dense
```

Once the slice of the tensor is clone and detach, then it works.

## Please reproduce using [the BoringModel and post here]
The issue can be reproduced below:
https://colab.research.google.com/drive/1yuqwb8BHhmDATp2IUNRNjSXOg3kV73Wp?usp=sharing

### Expected behavior
the metric update should work with a slice of tensor

### Environment

CUDA:
	- GPU:
		- Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.18.5
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.0.7
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by ananyahjha93** [comment]
@SkafteNicki I thought we solved something like this?

**Comment by SkafteNicki** [comment]
I also though we already fixed this.
@junwen-austin when I try to run the colab you linked to, I cannot reproduce. Is this only happening in ddp mode?

**Comment by junwen-austin** [comment]
@SkafteNicki Could you try the notebook again with the ddp (which I just updated). The issue was initially identified with ddp but you are right the issue does not replicate without ddp. I'll also update the post once you confirm this issue exists in the ddp model even with 1 GPU. Thanks.

**Comment by SkafteNicki** [comment]
So I can confirm that this happens when running in ddp mode, however I am not sure if this is a bug. It had nothing to do with `detach` bug we had some weeks ago.
This happens because `all_gather` requires all tensors to be `contiguous` (data is stored in an uninterrupted block of memory). When you take a slice of a tensor, you don´t alter the underlying memory location of data, just how you read it (basically changing the stride). If you try this in your code, you can see for yourself
```
print('output', output.is_contiguous()) # True
print('output slice', output[:,0].is_contiguous()) # False
```
the reason why calling `output[:,0].detach().clone()` works is that `clone` takes a contiguous copy of the data (the `detach()` is not nessesary). The more correct solution would be to call:
```
self.metric.update(output[:, 0].contiguous(),  
                   output[:, 1].contiguous())
```
We could easily implement calling `.contiguous()` inside the lightning metric on all tensors, however I at least want @ananyahjha93 opinion on this before moving forward.

**Comment by junwen-austin** [comment]
@SkafteNicki  thanks for the follow-up and good to know the more correct solution :)
