### ISSUE TITLE
How to remove hp_metric initial -1 point and x=0 points?

### ISSUE THREAD

**Issue by bartmch** [PyTorchLightning/pytorch-lightning#4832]
Hi, I don't think this is a bug but I'm doing something wrong. I want to use my val_dice as hp_metric tabular AND also see the graph on "show metric" (radio button) under the Tensorboard HPARAMS tab:
![image](https://user-images.githubusercontent.com/10415569/100072674-002dd180-2e56-11eb-80e0-2dcb94be0ae5.png)
To achieve this I'm logging using `self.log('hp_metric', mean_dice)` (for the graph) and `self.logger.log_hyperparams(params=self.hparams, metrics={'hp_metric': mean_val_dice})` (for the hparams value), both in the function `validation_epoch_end`
How do I get rid of the initial -1 value? How can I fix my graph so it doesn't draw any points at x=0? (zoomed in version)
![image](https://user-images.githubusercontent.com/10415569/100073169-9bbf4200-2e56-11eb-86d8-709ee3288fee.png)

**Comment by tchaton** [comment]
Hey @bartmch,

That's a great question ! Why do you want to see the metric under hparams tab ?

Best regards,
T.C

**Comment by rolanddenis** [comment]
As @bartmch, I use `hp_metric` to compare hyper parameters (is that not the purpose of this placeholder ?). I also have this negative initial value, but I didn't notice it before. I suppose it is not possible to remove this initial value but is there a way to customize it ?

**Comment by joe32140** [comment]
You can set `default_hp_metric` to False to prevent the initial hp_metirc score.
`TensorBoardLogger(save_dir='tb_logs', default_hp_metric=False)`

**Comment by rolanddenis** [comment]
Yes but then the `hp_metric` is not correctly tracked in the hparams (https://github.com/PyTorchLightning/pytorch-lightning/pull/2974)...

**Comment by joe32140** [comment]
There are two ways to track `hp_metric` for me after setting `default_hp_metric=False`. 

First, if you want to track hp_metric of every `validation_end`, you can `self.log('hp_metric', some_value)` in `validation_step`: then, I will compute the average of all steps in an epoch.

Second, if you only want to have one best value score for the whole training process, I set
```
trainer.fit(model)
        # track model performance under differnt hparams settings in "Hparams" of TensorBoard
tb_logger.log_hyperparams(params=model.hparams, metrics={'hp_metric': checkpoint_callback.best_model_score.item()})
tb_logger.save()
```
after `train.fit()` to make it work.

**Comment by rolanddenis** [comment]
I already use your first way but setting `default_hp_metric` to `False` makes `hp_metric` be removed from "hparams" tab (this tab isn't there at all even if I have set some hyper parameters). Adding the final `log_hyperparams` creates the hparams tab but the graph of `hp_metric` gets a final value at iteration 0 instead of final iteration), and this step will also be skipped if the job is killed.

Here are what I've tried so far:
- `default_hp_metric=True`: hparams tab visible in Tensorboad with `hp_metric` updated during training, `hp_metric` wrong initial value that makes the corresponding graph unsuitable with log scale and smoothing activated.
- `default_hp_metric=False`: no hparams tab in TensorBoard, `hp_metric` graph OK
- `default_hp_metric=False` and final `log_hyperparams`: no hparams tab in TensorBoard during training, `hp_metric` graph OK until the end of the training where final point is associated to iteration #0. No hparams tab at all if job is killed.

I will try to calculate metric before training start to appropriately populate it, or to delay `log_hyperparams` at the first validation...
