### ISSUE TITLE
Throw an exception when using manual_optimization with ddp

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning#4917]

**Comment by rakhimovv** [comment]
Can't run ddp with manual optimization too. Is this a bug?

Fails on the second batch with a error:
`RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.`
