### ISSUE TITLE
only run GPU tests on Drone

### ISSUE THREAD

**Issue by ydcjeff** [PyTorchLightning/pytorch-lightning#5205]
## 🚀 Feature

Only run GPU related tests on Drone

### Motivation
Currently we run all tests except tpu tests on Drone. Since cpu tests are all tested on various configs in github actions, it would be better to run gpu tests on gpu. If we only run gpu tests on gpu, we can probably run gpu tests with pytorch nightly.

### Pitch

To be able to run gpu tests with pytorch nightly

### Additional context

https://github.com/PyTorchLightning/pytorch-lightning/pull/4661#issuecomment-726990744
cc: @rohitgr7

**Comment by Borda** [comment]
there is no real need for this, the CPU tests are just a minute or two, so let's keep it rather than testing just special files and accidentally forgot that some test is not called...

**Comment by rohitgr7** [comment]
>  the CPU tests are just a minute or two

@Borda you sure about that? I see here in one of the CI with CPU resources runs for around 9 mins (just the tests).

**Comment by Borda** [comment]
> > the CPU tests are just a minute or two
> 
> @Borda you sure about that? I see here in one of the CI with CPU resources runs for around 9 mins (just the tests).

Ok, maybe more then 2 min =) 
But the point is to limit separation becase then it is very easy forget and write a naively test which never called...

**Comment by ydcjeff** [comment]
Shall we have like `gpu`, `cpu` or `on_cuda`, `on_cpu` or something like that?
When we do #5178 , so that we can run tests like `pytest . -k gpu`, `pytest . -k cpu`
WDYT?

**Comment by justusschock** [comment]
I wouldn't do that tbh. That is one more thing for contributors to remember. I prefer to use pytest.skipif(torch.cuda.is_available()) for cpu tests since that way if you forget to add it, the test is still executed and just test time increases. Whereas with the naming thing we may end up with tests being never executed.

**Comment by rohitgr7** [comment]
agreed with Justus here. Something like:
```python
accelerators_available = torch.cuda.is_available() or TPU_AVAILABLE or ...

@pytest.skipif(accelerators_available)
def test():
    ....
```

**Comment by Borda** [comment]
I still think that skipping some tests is addressing the root problem and makes the test week, as you as a contributor has a PC with GPU, then he won't run full tests unless he suppresses GPU visibility to his system... 
The problem is a single queue for all PRs, if we won't have 160 concurrency jobs for CPU, would you also run just some test for some configurations?

**Comment by rohitgr7** [comment]
can't this be done just with the CI tests somehow??
