### ISSUE TITLE
Loading checkpoint creates new logging directory and tries to load checkpoint from that directory

### ISSUE THREAD

**Issue by jloveric** [PyTorchLightning/pytorch-lightning#5274]
## 🐛 Bug

I'm doing training and then loading the checkpoint later to do some experiments.  I'm using hydra.  What's happening is the checkpoints are being created as expected.  However, after I load the checkpoint with load_from_checkpoint a new output directory is created, and the checkpoint attempting to be read from that new output directory (and so of course it can't find it).
```
if cfg.train is True :
        trainer = Trainer(max_epochs=cfg.max_epochs, gpus=cfg.gpus)
        model = Net(cfg)
        trainer.fit(model)
        trainer.test(model)
    else :
        # plot some data
        model = Net.load_from_checkpoint(cfg.checkpoint)
        model.eval()
        ...

**Comment by awaelchli** [comment]
Hi, could you help us reproduce this with the minimal bug report model found in the pl_examples folder? The `load_from_checkpoin`t function does not create new directories by itself, so there must be some other code in your case that creates this. When you use the `Trainer.test` method make sure to pass in the loaded model, otherwise it will attempt to load one.

**Comment by jloveric** [comment]
Turns out you need the full path otherwise it tries to load from a new path that it creates.  Not sure if this is just with Hydra or not.
