### ISSUE TITLE
Logging callback metric with `on_epoch=False` makes it invisible to ModelCheckpoint

### ISSUE THREAD

**Issue by indigoviolet** [PyTorchLightning/pytorch-lightning#5298]
## 🐛 Bug

Logging a metric in a callback with `on_epoch=False` and then using it as `monitor=` in `ModelCheckpoint` causes an error.

## Please reproduce using the BoringModel

https://colab.research.google.com/drive/1gruVIZALiS91B_nM6LxDSILekXejeZ5Y#scrollTo=i7XbLCXGkll9

### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Expected behavior

the metric should be usable as a monitor regardless of whether it is reduced on epoch.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !
* CUDA:
	- GPU:
		- Tesla T4
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.4
	- pyTorch_debug:     True
	- pyTorch_version:   1.7.0+cu101
	- pytorch-lightning: 1.1.2
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.6.9
	- version:           #1 SMP Thu Jul 23 08:00:38 PDT 2020

**Comment by rohitgr7** [comment]
do you think checkpointing while monitoring something logged at step level is correct??

**Comment by indigoviolet** [comment]
I guess the correctness of checkpointing based on step-level metrics depends on your batch size. 

In any case, I would not want the library to make this decision for me, or to at least not make this decision silently.

**Comment by edgarriba** [comment]
@indigoviolet we are looking at this issue with @carmocca . In principle, this behavior is intended, however, we are looking for a better solution to raise a more meaningful message in case of a misconfiguration similar to the one you are pointing.

**Comment by carmocca** [comment]
@indigoviolet

The current implementation doesn't allow monitoring something during validation at the step-level because it is assumed that the model will not change during validation. We consider this to be the better option to avoid potential errors.

Additionally, `ModelCheckpoint` supports saving `on_train_batch_end` (with the `every_n_train_steps` flag) but not `on_validation_batch_end` which would be also necessary to monitor something right after it is logged `on_step`.

Can you elaborate on what you are trying to accomplish and why would you need this constraint changed?

For reference, this is the `if` that would need to change:

https://github.com/PyTorchLightning/pytorch-lightning/blob/f67892ea963640389c9838eb716336afbb4f3826/pytorch_lightning/trainer/connectors/logger_connector/result.py#L556

cc @tchaton
