### ISSUE TITLE
LSTM training with hiddens in training_step()

### ISSUE THREAD

**Issue by bhashithe** [PyTorchLightning/pytorch-lightning#5372]
I am trying an LSTM network where I require in each training step the hidden value to be passed over to the next training step until the end of epoch. At the start of new epoch we reset by initializing the hidden to zeros. Following is how i do this, 

```
def training_step(self, batch, batch_nb, hiddens):
        ...
        if batch_nb == 0: #init only in new epochs
            hiddens = self.model.init_hidden(self.hparams.batch_size)
        out, hiddens = self.forward(posts, hiddens)
        ...
        loss = self.criterion(out, targets)
        return {'loss': loss, 'hiddens': hiddens}
```

As per the docs suggest, I've added the `truncated_bptt_steps` argument to `Trainer`, but it does not work as expected. It gives the following exception, 

`AssertionError: Batch time dimension length is ambiguous`

I've tried setting `truncated_bptt_steps=2` to different values but what ever value i set it results in the same exception. How does one train LSTMs like this with PTL? What am i doing wrong here?

PTL version 1.1.2

**Comment by tchaton** [comment]
Hey @bhashithe,

The error is being triggered there: https://github.com/PyTorchLightning/pytorch-lightning/blob/062800aa99cff6eb82838b355374305d9433507e/pytorch_lightning/core/lightning.py#L1260

Somehow, your hiddens don't have the right shape.

You can override this function to study in your LightningModule to understand what is wrong and add a custom behaviour.

If you think the bug is coming from us, please try to reproduce the behaviour with [bug_report_model](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py)

**Comment by bhashithe** [comment]
I am figuring out whether this is because of the `_split_batch` function or the hiddens shape. Let me get back to you guys.

**Comment by bhashithe** [comment]
@tchaton Thank you and you were spot on, I had to implement `tbptt_split_batch` function so that it behaves according to my data loaders.
