### ISSUE TITLE
Apply some previously ignored flake8 rules

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/pytorch-lightning#5748]
https://github.com/PyTorchLightning/pytorch-lightning/blob/ae14fca8b7ff0e1637f916a18097cb0557ff4ad2/setup.cfg#L84-L87

Each of these should be removed and format fixed in separate PRs
Context: #5739 

### Tracker:

- [x] E203
- [ ] E231
- [x] W504: Just remove, should not need formatting changes

Contributors are welcome 🤗

**Comment by akihironitta** [comment]
@carmocca Following W503 is not compliant with PEP8, and in my opinion, it also lowers readability. I'd suggest ignoring W503 instead of ignoring W504, or we could probably ignore both W503 and W504 like PyTorch does.
- https://www.flake8rules.com/rules/W503.html
- https://github.com/pytorch/pytorch/blob/5a402274d4939248b13b2b4e10629bc2ef66edb4/.flake8#L7

What  do you think?

**Comment by carmocca** [comment]
Sounds good to me. If we follow W504, we can just keep W503 in ignore, right? No need to ignore both

**Comment by akihironitta** [comment]
> If we follow W504, we can just keep W503 in ignore, right?

Yes, we can just keep W503 and remove W504 from the list in this issue.

**Comment by Borda** [comment]
there is a problem with E231 and `...` https://github.com/google/yapf/issues/897

**Comment by akihironitta** [comment]
Not directly related to this issue, but as observed in https://github.com/PyTorchLightning/pytorch-lightning/pull/5845#issuecomment-774428465, I think we should add `E121` to the ignore list (or change the yapf config to make it comply with `E121`).
