### ISSUE TITLE
Custom callbacks

### ISSUE THREAD

**Issue by alainjungo** [PyTorchLightning/pytorch-lightning#595]
It would be great if the [Trainer](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/trainer/trainer.py) could support any custom callbacks that follow the [Callback](https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/callbacks/pt_callbacks.py) structure.

**Comment by jeffling** [comment]
We've been talking about this for a while. 

One aspect I would like to add to this would be deterministic ordering of callbacks. It can be very difficult to maintain callbacks if the order of callback execution is not pre-defined, we end up having to handle a lot of edge cases for each callback as a result.

**Comment by jeremyjordan** [comment]
a very simple yet flexible way to achieve deterministic ordering is to use the order in which they're provided.

eg. `Trainer(..., callbacks=[custom_callback_1, custom_callback_2, model_checkpoint_callback])` would first call `custom_callback_1`, then `custom_callback_2`, etc.  for each hook

otherwise, enforcing order seems like a very daunting task.

**Comment by davidlrobinson** [comment]
As @jeremyjordan suggested, using a Keras-style ordered list of custom callbacks would be incredibly useful.

**Comment by Borda** [comment]
Yeah, after splitting callback in #849 we opened a discussion in #896...
@alainjungo do you have anything else you would add to this topic?
I would close this request in favour of  #896 so pls let's continue the discussion there :robot:
