### ISSUE TITLE
trainer.training_type_plugin.broadcast doesn't seem to work properly

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#6343]
### To Reproduce

Use following [**BoringModel**](https://colab.research.google.com/drive/1HvWVVTK8j2Nj52qU4Q4YCyzOm0_aLQF3?usp=sharing) and post here

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: Please, use our python [bug_report_model.py](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/bug_report_model.py
) template.

* `Colab Notebook`: Please copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py) (or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by edenlightning** [comment]
@justusschock mind taking a look?

**Comment by kaushikb11** [comment]
@tchaton Could you please elaborate on what exactly wasn't working properly while broadcasting?

**Comment by ananthsub** [comment]
@tchaton @carmocca I think there's definitely one issue with the model checkpoint, which is that the values for the `monitor` and for any monitor candidates that end up in the filename must be synced. Otherwise we end up with inconsistent filenames and state across ranks if we use the local values.

A separate issue we recently encountered is this:
Rank 0 has no issues with saving a checkpoint

Rank 1 throws an exception.
- which ends up being caught here: https://github.com/PyTorchLightning/pytorch-lightning/blob/966184a452c773a691b063195c817f3aed899f16/pytorch_lightning/trainer/trainer.py#L633-L635
- which leads to rank 1 re-entering the checkpoint flow because of this: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/trainer/training_loop.py#L130
- which causes the broadcast to hang!

**Comment by carmocca** [comment]
> @tchaton @carmocca I think there's definitely one issue with the model checkpoint, which is that the values for the `monitor` and for any monitor candidates that end up in the filename must be synced. Otherwise we end up with inconsistent filenames and state across ranks if we use the local values.

This has been reported here: https://github.com/PyTorchLightning/pytorch-lightning/issues/6138
