### ISSUE TITLE
JIT problem with `torchvision` 0.5

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning#694]
## 🐛 Bug

There are some JIT problems with newly released `torchvision` 0.5
in #687 we freeze version to <0.5 but in future, we want to support all `torchvision`s
Maybe it is just a temporal bug in `torchvision` and they will handle it...

### To Reproduce

https://github.com/PyTorchLightning/pytorch-lightning/pull/687#issuecomment-574913237

### Environment

https://app.circleci.com/jobs/github/Borda/pytorch-lightning/839

**Comment by 9dogs** [comment]
Based on https://github.com/pytorch/vision/issues/1383#issuecomment-536539662 `torchvision` now requires "recent enough" version of PyTorch. All tests are green with `pytorch==1.4.0` and `torchvision==0.5.0`. 
The problem is when `pytorch==1.3.0` is installed, `pip install torchvision` installs `torchvision==0.5.0` which is incompatible. Ah, I _love_ dependency issues...

**Comment by Borda** [comment]
Then the problem is `torchvision`, it shall enforce `torch >= 1.4.0`

**Comment by 9dogs** [comment]
But it does (starting from 0.4.0):
```
# pkginfo -f requires_dist torchvision-0.5.0+cpu-cp37-cp37m-linux_x86_64.whl
requires_dist: ['numpy', 'six', 'torch (==1.4.0)', 'pillow (>=4.1.1)', "scipy ; extra == 'scipy'"]
# pkginfo -f requires_dist torchvision-0.4.2+cpu-cp37-cp37m-linux_x86_64.whl
requires_dist: ['numpy', 'six', 'torch (==1.3.1)', 'pillow (>=4.1.1)', "scipy ; extra == 'scipy'"]
# pkginfo -f requires_dist torchvision-0.4.1+cpu-cp37-cp37m-linux_x86_64.whl
requires_dist: ['numpy', 'six', 'torch (==1.3.0)', 'pillow (>=4.1.1)', "scipy ; extra == 'scipy'"]
# pkginfo -f requires_dist torchvision-0.4.0+cu92-cp37-cp37m-manylinux1_x86_64.whl
requires_dist: ['numpy', 'six', 'torch (==1.2.0)', 'pillow (>=4.1.1)', "scipy ; extra == 'scipy'"]
```
My problem is I cannot freeze dependencies via pip-tools with `torch==1.4.0` since `pytorch-lightning` limits `torchvision` version.
Dirty solution is to manipulate `torch` version through `torchvision`, i.e. omit `torch` dependency in `requirements.txt` completely and set `torchvision>=0.4.0`.

**Comment by neggert** [comment]
Do we need the torchvision dependency at all? IIRC it is only used for tests and examples.

**Comment by williamFalcon** [comment]
1. idk why we would limit the version
2. not needed. We do need to add to the examples that people need to have torchvision and torch installed.

**Comment by Borda** [comment]
we are using MNIST dataset in tests `from torchvision.datasets import MNIST`

**Comment by williamFalcon** [comment]
so add torchvision to the tests requirements

**Comment by Borda** [comment]
but it is in package `pytorch_lightning.testing.base_model` so we would need to move it also out of the package or make own MNIT...

**Comment by kartikJ-9** [comment]
I have torch version 0.4.1, and torchvision->inception.py says that there is no module named call Optional in torch.jit.annotations....I want to use torch version 0.4.1 because I want to use it along with cuda 9.2 for my program. And as per my understanding, torchvision requires torch 1.4. How do I solve this dependency problem?

**Comment by Borda** [comment]
are you talking about `torch==0.4.1` or `torchvision=0.4.1` this is not related to lightning, you shall ask at torch/vision
