### ISSUE TITLE
Add test running predict inside the LightningModule hooks

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#7333]
### Motivation

This should work. Add a test to make sure this works reliably in multi-gpu setting. 

```python

class MyModel(pl.LightningModule):
    def on_training_epoch_start():
        # calling trainer.predict inside trainer.fit routine.
        # is this okay?
        pred_outputs = self.trainer.predict(dataloaders=self.datamodule.train_loader)
        # do some work with pred_outputs
# start training
model = MyModel()
trainer = Trainer(model, accelerator='ddp')
trainer.fit()

```
### Pitch

Add a test. Integrate findings in future loop design. 

### Alternatives

User can write their own predict loop inside the hooks, but is error prone and untested.

### Additional context

Asked on slack by Dilip Thiagarajan

**Comment by carmocca** [comment]
We do not support this as it would overwrite the trainer state.

It's something we could explore but it can open a can of worms as then people would expect to be able to call `fit` again, or `validate`, etc.

The recommended approach at the moment is to chain `fit` and `predict` calls one after the other, although there are other limitations there such as having to recreate the `Trainer` instance.

**Comment by bw4sz** [comment]
This continues to be a really sore area for me. @carmocca have you seen any cases about when to recreate a trainer instances, anything I should look out for? I love trainer.predict because its so much more efficient than looping through batches manually, but it can't be used inside callbacks (as in many issues in this repo), so now i'm creating a new trainer each time the callback is made.
