### ISSUE TITLE
ModelCheckpoint Filepath Doesn't Use Logger Save Dir

### ISSUE THREAD

**Issue by collinmccarthy** [PyTorchLightning/pytorch-lightning#734]
# 🐛 Bug

Not sure if this is intended, but the model checkpoint isn't using the same directory as the logger, even if the logger exists. I would have expected this line [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/588ad8377167c0b7d29cf4f362dbf42015f7568d/pytorch_lightning/trainer/callback_config.py#L28) to be `self.logger.save_dir` instead of `self.default_save_path`. 

Thank you,
-Collin

**Comment by bosbes** [comment]
I am running into the same issue and feel like I must be doing something wrong. If I do not define a logger and checkpoint callback, the logger and checkpoint are saved in a clear structure under lightning_logs. But if I do provide them, it turns out to be difficult to get Lightning to follow that same structure. If I use lightning_logs as filepath I get the warning that that directory already exists and that my existing checkpoints will be overwritten.

**Comment by sneiman** [comment]
Were you able to find the checkpoints? I cant seem to find them anywhere!

**Comment by collinmccarthy** [comment]
The checkpoints are currently being saved to a subfolder of the current working directory. If you print the current working directory at the top of our file with `print(os.getcwd())` that should tell you where to find them.

**Comment by sneiman** [comment]
FWIW, using the default checkpoint_callback, the checkpoint is not in default location. Still looking for it! Though no more default checkpoint_callback for me ...
