### ISSUE TITLE
Question with global_step and every_n_train_steps

### ISSUE THREAD

**Issue by jungwhank** [PyTorchLightning/pytorch-lightning#7496]
## 🐛 Bug

Hi, 
I'm trying to use `every_n_train_steps` in ModelCheckpoints callback and I have an issue about it.
As show in below colab, I guess it should save steps with `10, 20, 30`, but It saves steps with `9, 19, 29`.

Did I misunderstand about `trainer.global step` or something with callback?

As an additional question, Is `save_last` option just overwrite the last saved checkpoint as `last.ckpt`? 

### To Reproduce

https://colab.research.google.com/drive/1s0F0sKQpcs136ciFSq4Aft3RY-jJJ8oA?usp=sharing

### Expected behavior

I think it should save steps at 10, 20, 30

### Environment

```
* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.8.1+cu101
	- pytorch-lightning: 1.3.1
	- tqdm:              4.41.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.10
	- version:           #1 SMP Tue Apr 20 19:55:43 PDT 2021
```

**Comment by awaelchli** [comment]
Hi
The current behavior is that the global step value in the checkpoint file corresponds to the logging step observed in the logger, which means the first step is logged/saved at 0 (0 indexed). That's why you see 9, 19, 29, etc. 

It may change in the future #6997 

> As an additional question, Is save_last option just overwrite the last saved checkpoint as last.ckpt?

last.ckpt is an additional file which is identical to the previously last saved checkpoint, the only difference is that the name is deterministic (just last.ckpt).

**Comment by jungwhank** [comment]
Thanks for answering!
