### ISSUE TITLE
Lightning CLI is not aware of PL_TRAINER_* environment settings

### ISSUE THREAD

**Issue by awaelchli** [PyTorchLightning/pytorch-lightning#7887]
## 🐛 Bug

Without the LightningCLI, the Trainer parses the arguments from environment variables when provided. But with when using the new CLI, this does not happen.

### To Reproduce

```bash
# GOOD: runs on 2 GPUS, does not use Lightning CLI
PL_TRAINER_GPUS="2" python bug_report_model.py

# BUG: runs on CPU, this example uses LightningCLI
PL_TRAINER_GPUS="2" python basic_examples/simple_image_classifier.py 

# GOOD: works as expected
python basic_examples/simple_image_classifier.py --trainer.gpus 2
```

### Expected behavior

Runs with arguments overridden from environment. This is needed for Grid, i.e., we want to be able to run on grid like so:

```bash
grid run --gpus 8 --instance_type 4_v100_16gb train.py 
````

without the need to set explicitly the `--trainer.gpus` flag again. Afaik Grid passes some arguments to Lightning via the environment variables.

**Comment by awaelchli** [comment]
@mauvilsa you may know what the reason for this is, but if not, I can investigate too. 

What I  know is that there is a decorator on the constructor of our Trainer
https://github.com/PyTorchLightning/pytorch-lightning/blob/5593b6f772c75ae016580e2579c2af9f86b19a39/pytorch_lightning/trainer/trainer.py#L95

Not sure how easy it is to fix.

**Comment by mauvilsa** [comment]
I did not know how the `@_defaults_from_env_vars` worked. The reason is that the parser gets the defaults from the signature and then the Trainer class is instantiated giving all values. Since in [env_vars_connector.py#L37](https://github.com/PyTorchLightning/pytorch-lightning/blob/5593b6f772c75ae016580e2579c2af9f86b19a39/pytorch_lightning/trainer/connectors/env_vars_connector.py#L37) the `env_variables` are on the left then they always get overridden.

There is a way to enable parsing of environment variables from jsonargparse, see [cli.py#L105](https://github.com/PyTorchLightning/pytorch-lightning/blob/5593b6f772c75ae016580e2579c2af9f86b19a39/pytorch_lightning/utilities/cli.py#L105). If we enable this in the CLI there is the benefit that user defined modules could also be configured using environment variables.

How does `grid run --gpus 8` become `PL_TRAINER_GPUS=8`? Is this mapping hard coded in grid run?

The only caveat of jsonargparse is that the environment variable names are different. It would be `PL_TRAINER__GPUS`. If it is important that the names match exactly, then a small change in jsonargparse would be required.

**Comment by awaelchli** [comment]
> How does grid run --gpus 8 become PL_TRAINER_GPUS=8? Is this mapping hard coded in grid run?

Actually, found out now that Grid used to do it but not anymore, my expectations were wrong. So it seems to me that this environment parsing is now only used internally in Lightning. We can remove Grid from the discussion here. 

Found there are a few usages by random projects
https://github.com/search?p=3&q=PL_TRAINER_GPUS&type=Code
but mainly to fix problems that arise from this internal use itself. I now think, if possible, we should try to remove it entirely.

**Comment by alvis** [comment]
I haven't tested it, but when I was debugging for another issue, I see the following in LightningCLI's docstring:
https://github.com/PyTorchLightning/pytorch-lightning/blob/0004216f2f90c39afdb938eff41ec73458f858f3/pytorch_lightning/utilities/cli.py#L130-L133

Hope this helps. ;)
