### ISSUE TITLE
Remove default monitor value from the EarlyStopping callback

### ISSUE THREAD

**Issue by ananthsub** [PyTorchLightning/pytorch-lightning#7894]
## 🚀 Feature

Remove the default for the Early Stopping callback's monitor: https://github.com/PyTorchLightning/pytorch-lightning/blob/b214442e745e9400e4f842d406939b4e2cd33390/pytorch_lightning/callbacks/early_stopping.py#L91

### Motivation

This is a holdover from pre-1.0 when the Result object defined this key. We should remove the default for these reasons:
- It's possible to construct an EarlyStopping callback without setting this. This can lead to runtime issues during training in case the default key (`early_stop_on`) isn't found in the list of available metrics. Since this happens at the end of either training or validation, this can waste a ton of time compared to failure on construction before training starts.
- We don't want to recommend or suggest that people must log this key within their lightning module to get early stopping to work. `self.log("early_stop_on", <val>)`

### Pitch

Deprecate the default value and force users to explicitly provide a monitor

**Comment by bamblebam** [comment]
Hey I am new to pytorch. Can I help ?

**Comment by awaelchli** [comment]
@bamblebam Welcome!
Unless @ananthsub has already prepared or started a branch, you could try to remove the monitor default and check which tests need updating. As Ananth said, we need to add a deprecation message printed if someone does not provide the argument. 

Also, since you said you are new, here is the [contributing guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), you may find it helpful 😃
