### ISSUE TITLE
[RFC] Checkpointing in Lightning: Create a new CheckpointAgent interface for placing checkpointing logic

### ISSUE THREAD

**Issue by RahulMitra** [PyTorchLightning/pytorch-lightning#8118]
## 🚀 Feature
with: @haocizhang

We propose a new `CheckpointAgent` interface to contain all the logic that is related to checkpointing (currently residing in `TrainingTypePlugin` and `CheckpointConnector`). This includes serialization, deserialization as well as the logic to read/write to file systems. This will enable greater extensibility for custom implementations of checkpointing, such as the ones we utilize internally at Facebook.

### Motivation

At Facebook, business requirements have driven us to scale the size of our largest ML models, leading us to develop a distributed training stack for training our largest models. As such, our implementation of checkpointing has diverged from the typical PyTorch open source methods. We are committed to integrating our internal stack at FB into the lightning framework, however we must reconcile these differences:

* **Sharding of large models**: Our embedding tables no longer fit on one GPU, so we shard tensors across ranks. As such, we do not use `state_dict` and `torch.save` / `torch.load` semantics, as we operate with sharded tensors and use a `sharded_state_dict`.
* **Saving many model instances(i.e. snapshots) of the same model series**: this made us support checkpoint versions instead of flushing different snapshots to the same user defined path
* **Implementing async checkpointing to unblock training progress:** due to the size of our models, uploading our checkpoints to our network storage service places a high amount of load on them, and also blocks training progress. With async checkpointing, we pause training, stage checkpoints to DRAM or SSD, then resume training while uploading the staged checkpoints to network storage in the background.

We anticipate that a subset of these features may be useful for the open source community and are actively working on open sourcing many of them. In the meantime, we are also thinking about what would be an implementation of checkpointing in Lightning that makes it easiest to extend and support those features in the future.

### Issues faced with current design

Currently, Lightning performs checkpointing by dumping the trainer’s states into a dict before serializing it and finally flushing it to persistent storage. When saving and loading checkpoints, some of the logic happen in `CheckpointConnector` (e.g. restoring optimizer states), while others are executed through callbacks (e.g. dumping the states of some variables into the dict).

Given our model architecture, we have faced some of the following issues integrating our training stack with Lightning:

1. Some of the logic for dumping and loading checkpoints happens in `CheckpointConnector`, which is not an extendible interface that can be passed into the trainer.
2. Training type plugin does I/O using API calls provided by `fsspec`. It is possible to implement cloud storage APIs into `fsspec` including async operations in the future, but `fsspec` only provides pure I/O interfaces and does not allow more custom logic in the serialization/deserialization or the write/read process. For example, instead of solely writing the object to the predefined path, users might want to implement versioned checkpointing by fetching the last checkpoint version, incrementing the version, appending the new version to the checkpoint path, flushing out the bytes and committing some metadata to the database. A good external comparison for our internal implementation of these features is the [ML Flow's tracking client](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores).

### Proposed design

We propose a new `CheckpointAgent` interface to contain all the logic that is related to checkpointing (currently residing in `TrainingTypePlugin` and `CheckpointConnector`). This includes serialization, deserialization as well as the logic to read/write to file systems.  

```python
CheckpointAgentInterface(ABC):
   def save_checkpoint(self, ckpt, path): 
      # Put all logic related to saving checkpoint here
      
   def load_checkpoint(self, path):
      # Similarly, put all logic related to loading checkpoint here
   
   def delete_checkpoint(self, path):
      # Similarly, put all logic related to deleting checkpoint here
```

To see how we organize the code with this new interface, let's take the save checkpoint path as an example and examine the current behavior, as well as the behavior with the proposed changes:

#### Currently:

Responsibilities of different classes:
* `CheckpointCallback`: Able to put customized information into the checkpoint dict when `on_save_checkpoint` is called, which would eventually be flushed to persistent storage.
* `TrainingTypePlugin`: Calls cloudio’s IO functions to flush dict to predefined path when saving checkpoints, contains some functions to load certain model states from a dict which would be needed when loading checkpoints.
* `CheckpointConnector`: Gathers various trainer states into checkpoint dict when saving checkpoints, contains some logic to restore states when loading checkpoints as well as calling some functions in `TrainingTypePlugin`.

```python
CheckpointConnector:
   def dump_checkpoint():
      # logic here
      
   def save_checkpoint():
       ckpt = dump_checkpoint()
       self.trainer.accelerator.save_checkpoint(ckpt, filepath)
       
TrainingTypePlugin:
   def save_checkpoint():
        atomic_save(checkpoint, filepath)
```

#### Proposed Changes:

Responsibilities of different classes:
* `CheckpointCallback`: Able to put customized information into the checkpoint dict when `on_save_checkpoint` is called, which would eventually be flushed to persistent storage. (Same as before)
* `TrainingTypePlugin`, `CheckpointConnector`: Pass through classes that do not contain actual logic besides eventually calling into functions of `CheckpointAgent`. In the load checkpoint path, `CheckpointConnector` would also execute the trainer’s `on_load_checkpoint hook` so the corresponding callbacks can be executed.
* `CheckpointAgent`: Contains the functionalities that previously belonged to `TrainingTypePlugin` and  `CheckpointConnector`. This includes interacting with external storage wrappers, dumping model states into the [str, Any] dict and restoring models from a dict.

```python
CheckpointConnector:
   def save_checkpoint():
       self.trainer.accelerator.save_checkpoint()
       
TrainingTypePlugin:
   def save_checkpoint():
        checkpoint_agent.save_checkpoint()
        
CheckpointAgentInterface(ABC):
   def save_checkpoint(self, ckpt, path): 
      # Put all logic related to saving checkpoint here
      
   def load_checkpoint(self, path):
      # Similarly, put all logic related to loading checkpoint here
   
   def delete_checkpoint(self, path):
      # Similarly, put all logic related to deleting checkpoint here
```

We can support a default implementation of the `CheckpointAgent`, which provides the current behavior by simply being a container for the `save_checkpoint`, `dump_checkpoint` logic in `CheckpointConnector` and the `save_checkpoint` logic in `TrainingTypePlugin`:

```python
FileBasedCheckpointAgent(CheckpointAgentInterface):
    # Path will be passed into trainer during construction, 
    # ckpt dict will be constructed in connector
    def save_checkpoint(self, ckpt, path):
        # originally in training type plugin, checkpoint connector and cloud io
        dump_checkpoint(ckpt)
        with fsspec.open(path, "wb") as f:
            f.write(ckpt)
        
    def load_checkpoint(self, path):
        # originally in training type plugin, checkpoint connector and cloud io
        # the path is provided to the checkpoint callback constructor
        fs = get_filesystem(path)
        ckpt = {}
        with fsspec.open(path, "rb") as f:
            ckpt = torch.load(f)
        lightning_module.load_state_dict(ckpt["state_dict"])
        load_model_state_dict(ckpt)
        return ckpt
```

Because this new `CheckpointAgent` interface is simply a container for the logic that originally resided within the `CheckpointConnector` and `TrainingTypePlugin`, we now gain the freedom to provide custom implementations of checkpointing, for example passing in an `AsyncCheckpointAgent` into the trainer. By providing a default implementation that implements the current checkpointing behavior in Lightning, we do not change support for the existing checkpoint hooks or callbacks of upper layers. 

In addition to the default implementation, in the future we may add other agents to support advanced use-cases such as async checkpointing and checkpointing for sharded models.

**Comment by haocizhang** [comment]
cc: @ananthsub, @kandluis

**Comment by ananthsub** [comment]
I think this will be a very useful addition to make the IO pluggable. @carmocca @awaelchli - do you think this would be useful for WandB or other logger clients like MLFlow mentioned in the issue around publishing model artifacts? 

Some of questions:
- Where should the CheckpointAgent reside / what invokes the agent? For example, is does the trainer own it, but the checkpoint callback invokes it via the trainer to save? The agent can't directly live on the callback as we need to support resuming from checkpoint without passing in a callback instance.

- Should we support multiple agents? For example, what if someone wants to publish both to a remote service and local file at the same time? Or if someone wants to load from a remote service but save to a local file?

**Comment by haocizhang** [comment]
- Yes, you are correct that it cannot be owned by the callback and has to be owned by the trainer. On the `save_checkpoint()` path, the plan is to keep the current implementation and have `checkpoint_callback` invoke `trainer.save_checkpoint()` from its `_do_save()` function, which then calls `checkpoint_connector.save_checkpoint()`, passes the agent to the plugin and finally invoke `checkpoint_agent.save_checkpoint()`.

- We haven't thought of having multiple agents, both because we do not currently have an internal use case for this and because of the potential complexity it brings. For example, aside from the possible cases you mentioned, what if someone wants to save the different structures of the trainer to different storage solutions? And how would we load all these checkpoints to resume the training process in this case? That being said, 
    -  It shouldn't be hard to extend the agent interface for supporting multiple FS as a custom checkpoint agent implementation (pseudocode shown below).
    - We believe that we can hold off on this for now and consider open sourcing this when there is an actual demand and more concrete examples.
```python
class CustomCheckpointAgentHack(CheckpointAgentInterface):
     def __init__(self, list_of_checkpoint_agents):
          self.agents = list_of_checkpoint_agents

     def save_checkpoint(self, ckpt, path):
          dump_checkpoint(ckpt)
          for agent in agents:
               agent.flush_checkpoint(ckpt, path)
```

**Comment by tchaton** [comment]
Hey @RahulMitra,

Definitely a great proposal ! 

`Where should the CheckpointAgent reside / what invokes the agent?`
I believe the `CheckpointAgentInterface` should be own by the `TrainingTypePlugin` as the way to share a given checkpoint is dependent on the Plugin, c.f DeepSpeed / FSDP.

And users could use the Plugin registry to make their TrainingType plugin + desired  `CheckpointAgent` easier to instantiate.

Best,
T.C

**Comment by ananthsub** [comment]
> I believe the CheckpointAgentInterface should be own by the TrainingTypePlugin as the way to share a given checkpoint is dependent on the Plugin, c.f DeepSpeed / FSDP. And users could use the Plugin registry to make their TrainingType plugin + desired CheckpointAgent easier to instantiate.

This would mean creating (# of plugins x # of checkpoint agent implementations) for the plugin though. 

I wonder if we could create this interface as a new type of Plugin, e.g. rename `CheckpointAgent` instead of `CheckpointAgent` . 

Then we could bind the plugin to the trainer on trainer construction, or default to the fsspec-based plugin if none are passed in. 

From the checkpoint connector, we could then pass the checkpoint plugin to the training type plugin as part of `save_checkpoint` or `load_checkpoint`

The base implementation for these could simply be `checkpoint_plugin.{save/load}_checkpoint(checkpoint_dict, path)`, but it allows deepspeed to do custom things with its engine. maybe that could be a feature request for deepspeed 

what do you think @tchaton ?

**Comment by tchaton** [comment]
Hey @ananthsub, I think this won't work for DeepSpeed as it needs to actually save the checkpoint to file system.

But could we have this API ? @SeanNaren 

```
CheckpointIOPlugin

    def save_checkpoint(checkpoint, path):

    def load_checkpoint()


# saving
paths = self.training_type.save_checkpoint(checkpoints, path)
for path in paths:
    checkpoint = torch.load()
    self.checkpoint_io_plugin.save_checkpoint(checkpoint, path)

# loading
self.checkpoint_io_plugin.load_checkpoint(path)
self.training_type.load_checkpoint(path)
```

**Comment by SeanNaren** [comment]
I see a main goal here to make checkpointing extendable in one place, rather than the current separation across classes (correct me if I'm wrong).

Firstly I'm for the TrainingTypePlugin to own this checkpoint plugin. However if a user passes a checkpoint plugin to the trainer, what should be the appropriate action? Replace the checkpoint plugin regardless of the TrainingTypePlugin chosen? This would probably break DeepSpeed/Sharded training unless the logic was included, but I think for a first pass this is ok (we can also throw an exception in this special case).

Regarding the above API @tchaton thanks for the discussion! After familiarising myself with the issue, the proposed pseudocode is a fix for one of the issues (having more information to add custom logic in a callback function) but doesn't allow users to override the actual saving logic which seems to be more crucial long term. I think i prefer just carving out a checkpoint plugin for that reason!

Do we see any other sticking points that I'm missing?

**Comment by ananthsub** [comment]
> Firstly I'm for the TrainingTypePlugin to own this checkpoint plugin. However if a user passes a checkpoint plugin to the trainer, what should be the appropriate action? Replace the checkpoint plugin regardless of the TrainingTypePlugin chosen? This would probably break DeepSpeed/Sharded training unless the logic was included, but I think for a first pass this is ok (we can also throw an exception in this special case).

Deepspeed is a special case since checkpointing is baked into the deepspeed engine. In this case, we could raise a warning or exception if the checkpoint plugin is incompatible with the training type, but the training type should retain this flexibility. This would mean the validation for compatibility & final behavior of whether to use the plugin is still determined by the training type. 

In many other cases, this separation between IO and checkpoint generation/loading logic is clearer, which is where carving out this interface makes sense. 

@SeanNaren @tchaton would this address your concerns?

**Comment by xunnanxu** [comment]
Thanks @RahulMitra for the logic reorganizing proposal. A couple of minor comments:
1. Naming wise, instead of calling it `CheckpointAgent`, maybe we can be more specific like `CheckpointExecutor` or `CheckpointIOHandler`. One reason is there are a dozen of `save_checkpoint()` callbacks in lightning and it would be a bit more confusing to users which one actually does the real save after more layers are introduced. Another reason is `Agent` is an already taken word in internal checkpointing world so that would avoid unnecessary context misunderstanding with general pytorch stack.

2. How do we plan to handle errors long term especially when IO becomes async to handle expensive calls (e.g. saving to distributed file system with huge models). This is not required in the context of this proposal but want to see how we plan to extend the agent interface (maybe another callback later on like `on_checkpoint_save_error()`?)

**Comment by ananthsub** [comment]
@SeanNaren @RahulMitra @haocizhang following up here since it's been a while from when the initial issue was filed, and some of our motivations for the plugin have been solved in more elegant ways.

- A primary motivation was to support saving and loading of sharded tensors with this dedicated plugin. This is why the `LightningModule` was initially required in the `CheckpointPlugin`. However, with https://github.com/PyTorchLightning/pytorch-lightning/issues/8633 and https://github.com/pytorch/pytorch/pull/62242 , sharded tensors will now appear directly in the lightning module's state dict. that means less special handling required at the training type plugin or IO plugin level.
- Because there's less handling required here, it doesn't make to bifurcate the existing model ownership logic. It should remain that the training type plugin "owns" the lightning module and optimizer and handles loading/saving their states from the checkpoint dict.
- This allows the CheckpointIO Plugin to focus exclusively on the IO aspects, especially for use cases that need a generalization beyond fsspec (e.g. it might be more straightforward to use an existing client than wrap this client in fsspec's FileSystem API)
- This allows us to dramatically simplify the plugin API and avoid any recursive dependencies between Checkpoint & Training Type Plugin. It essentially is what @tchaton posted here: https://github.com/PyTorchLightning/pytorch-lightning/issues/8118#issuecomment-871406133 . 
- The training type plugin can still determine which ranks save the checkpoints, and how the checkpoint plugin gets called . 
- We still need a good way to "enrich" the training type plugin with the checkpoint plugin. This is a similar need for Cluster Environments, so we should rethink the lazy-init style for Training Type Plugins. Relying on `hasattr` is getting more fragile inside the accelerator connector. This could warrant a direct property & setter on the training type plugin API
- @xunnanxu - We still need more details on how we should support async checkpoint saving. error handling and signaling in-flight checkpoints being saved both warrant more discussion

**Comment by awaelchli** [comment]
> We still need a good way to "enrich" the training type plugin with the checkpoint plugin. This is a similar need for Cluster Environments, so we should rethink the lazy-init style for Training Type Plugins. Relying on hasattr is getting more fragile inside the accelerator connector. This could warrant a direct property & setter on the training type plugin API

I created an issue here a while back: #7650. Maybe it's helpful.

**Comment by SeanNaren** [comment]
Makes a lot of sense @ananthsub thank you for the update and linking to the Sharded Tensor stuff, will take some time to play around with it :)

I agree, I was very unsure about where to draw the boundary across this `CheckpointPlugin` and the `TrainingTypePlugin`. Your motivation also confirms that we should try to bring all IO behaviour (`rm`) as well into this plugin! Will remove the state dict loading once in memory from the plugin.

**Comment by SeanNaren** [comment]
thanks for all the feedback guys! The interface is available on Master now, with instructions here: https://pytorch-lightning.readthedocs.io/en/latest/advanced/checkpoint_io.html
