### ISSUE TITLE
Support multiple loggers at once

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#825]
## 🚀 Feature
Users might want to use more than 1 loggers at once

**Comment by ethanwharris** [comment]
A good way to do this might be to create a `ListLogger` class or similar that takes a list of loggers and iterates over them on each call. Can then make this happen auto-magically in the `Trainer` when a list of loggers is given. Any issues with this approach @PyTorchLightning/core-contributors ? Otherwise I'm happy to implement it :)

**Comment by Borda** [comment]
The `LoggerCollection` sounds good, a user would pass list loggers he wants to use and then under the hood, it will be transformed to this wrapper...
Moreover, we may do the same, simplified API, with callbacks... as e.g. Keras did, pass just list of callbacks to be executed and Trainer will call then when needed instead of having them specified
https://github.com/PyTorchLightning/pytorch-lightning/blob/b1040523b2180300574d961444b00abfa3c84195/pytorch_lightning/trainer/trainer.py#L65

**Comment by ethanwharris** [comment]
Yeah, that sounds good, I'll do this for Loggers first and then we can think about following up for callbacks

**Comment by williamFalcon** [comment]
why not just take in the list of loggers

```
Trainer(loggers=[a, b, c])
```

And anytime we call the logger right now internally, we replace with a call to all of them.

**Comment by ethanwharris** [comment]
The value of a `LoggerList` object or similar here is that the `Trainer` code doesn't need to care how the `Logger`s were given except in the init where it wraps them. The API the user sees will be the same, but it seems more encapsulated this way. That said, either option is fine in that they will both give the same result. Any strong opinions for either option? Otherwise I tend towards a `LoggerList`

**Comment by Borda** [comment]
as I mentioned, we would keep the API as Will gave [example](https://github.com/PyTorchLightning/pytorch-lightning/issues/825#issuecomment-588232977) but under the hood, we would use a class iteration loggers co you do not repeat looping over all logger or checking if there is just one or more...

**Comment by williamFalcon** [comment]
Yeah, i think under the hood a loggerlist or some class to encapsulate makes sense! To the user though they should just intuit that they can pass in a list of loggers.

@srush thoughts?

**Comment by srush** [comment]
Yup, the user API of torch-lightning seems to be that passing/returning lists just works, so I like that style.

**Comment by ethanwharris** [comment]
Closed by #903

**Comment by RAraghavarora** [comment]
Can we multiple loggers to use for different metrics?
For example, when I log the train_loss, I want it to be in a separate file than val_loss:
```
weight_change_logger = CSVLogger('logs', name='weight_changes')
train_loss_logger = CSVLogger('logs', name='train_loss')
val_loss_logger = CSVLogger('logs', name='val_loss')
```

**Comment by vidhi0206** [comment]
> Can we multiple loggers to use for different metrics? For example, when I log the train_loss, I want it to be in a separate file than val_loss:
> 
> ```
> weight_change_logger = CSVLogger('logs', name='weight_changes')
> train_loss_logger = CSVLogger('logs', name='train_loss')
> val_loss_logger = CSVLogger('logs', name='val_loss')
> ```

Did you get the answer of how to do it? I am not able to find the answer

**Comment by RAraghavarora** [comment]
> > Can we multiple loggers to use for different metrics? For example, when I log the train_loss, I want it to be in a separate file than val_loss:
> > ```
> > weight_change_logger = CSVLogger('logs', name='weight_changes')
> > train_loss_logger = CSVLogger('logs', name='train_loss')
> > val_loss_logger = CSVLogger('logs', name='val_loss')
> > ```
> 
> Did you get the answer of how to do it? I am not able to find the answer

No... I didn't, and ended up giving up on it.
