### ISSUE TITLE
Why are there additional processes when I use Horovod?

### ISSUE THREAD

**Issue by marsggbo** [PyTorchLightning/pytorch-lightning#8336]
## 🐛 Bug

I was trying to use Horovod for distributed training, but I found that `lightning` created more processes  on GPUs than I specified. 

For example, when I use 4 GPUs, it will create 7 processes, where there are 3 additional processes. 

![image](https://user-images.githubusercontent.com/13477956/124939755-f8fdb180-e03b-11eb-9093-2be0218ee1b3.png)

When I use 2 GPUs, it will create 3 GPUs, where there is 1 additional process. 

![image](https://user-images.githubusercontent.com/13477956/124940040-35311200-e03c-11eb-9a68-6782d9169cea.png)

We can see that all additional processes occupied 1313 MB of memories. I want to ask what these processes are and why they are created?

This is a video recording of the memory changes when using four GPUs

<video src="https://user-images.githubusercontent.com/13477956/124941668-90173900-e03d-11eb-9e26-11c441970dd7.mp4"></video>

 - PyTorch Lightning Version 1.3.8:
 - PyTorch Version 1.8.1
 - Python version: 3.8.0

cc @awaelchli @akihironitta

**Comment by Borda** [comment]
@marsggbo seems the video can't be shown

**Comment by marsggbo** [comment]
sorry, you may refer to this url: https://youtu.be/6AEaTESPhAM

**Comment by marsggbo** [comment]
Is any possible reason to explain this phenomenon?

**Comment by jdcla** [comment]
I seem to be having the same phenomenon on my code.

**Comment by awaelchli** [comment]
I think that's because you specified gpus=X in the Trainer and launched also using horovodrun. 
It's important that the number of devices is set to 1 in the Trainer and only the horovodrun command should set the devices. 

We tried to make it as clear as possible in the [docs](https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu.html#horovod).
Any suggestion for an improvement there? Maybe a colored info box or even a warning. 

Furthermore, we should probably improve the messaging from the framework side as well. The horovod plugin or the accelerator connector should do a better job validating the inputs here. Any contributions or suggestions on this side would welcome.
