### ISSUE TITLE
Force disable early stop feature documentation is not correct

### ISSUE THREAD

**Issue by jeremyjordan** [PyTorchLightning/pytorch-lightning#857]
## 📚 Documentation

In the [latest docs](https://pytorch-lightning.readthedocs.io/en/latest/early_stopping.html#), it says:

> To disable early stopping pass None to the early_stop_callback
```
trainer = Trainer(early_stop_callback=None)
```

However, if you look at the code for the `TrainerCallbackConfigMixin` this is not what happens.

```

def configure_early_stopping(self, early_stop_callback):
    if early_stop_callback is True:
        ...
    elif early_stop_callback is None:
        self.early_stop_callback = EarlyStopping(
            monitor='val_loss',
            patience=3,
            strict=False,
            verbose=False,
            mode='min'
        )
        self.enable_early_stop = True
    ...
```

What is the intended behavior? One of these two things should be updated.

**Comment by kuynzereb** [comment]
Docs should be updated. To disable early stopping one should set `early_stop_callback=False`. By default `early_stop_callback=None` and it initializes not strict version of early stopping. It means that it will work only if the user returns `'val_loss'` after `validation_end()` and otherwise training will go as though early stopping is disabled.
