### ISSUE TITLE
fix segmentation demo

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#874]
@akshaykvnit @Borda

```
 ERROR collecting pl_examples/full_examples/semantic_segmentation/semseg.py

 No module named 'torchvision.models.segmentation'
oops, looks like this test fails. Need to fix asap
```

**Comment by akshaykvnit** [comment]
@williamFalcon
According to [this page](https://pytorch.org/docs/stable/torchvision/models.html), it does exist. Not sure why it fails.

**Comment by williamFalcon** [comment]
probably has  to do  with the  version of  torchvision which i noticed  isn't being checked or anything

**Comment by akshaykvnit** [comment]
@williamFalcon
According to [this page](https://pytorch.org/blog/torchvision03/), segmentation models were introduced in version 0.3 of torchvision. So, I think the tests might be using older versions (for backwards compatibility maybe?)

What I can do is add a custom implementation of U-Net (popular architecture) and replace the torchvision model. But even that'll take a few hours because I have some work right now.

**Comment by williamFalcon** [comment]
@akshaykvnit yes please. That would be ideal. This is breaking the core tests, so we'll have to roll this back otherwise.

Thanks!

**Comment by Borda** [comment]
@williamFalcon major question is what torchvision version do you want to support, in past we had there `torchvision>=0.4`

**Comment by akshaykvnit** [comment]
> @williamFalcon major question is what torchvision version do you want to support, in past we had there `torchvision>=0.4`

I would also suggest keeping `torchvision>=0.3` at least because a lot of object detection and segmentation models were introduced in 0.3. These are very good architectures which will be good for examples, instead of using custom models.

**Comment by Borda** [comment]
Note that this package is not dependent on `torchvision` any more, just some tests and examples...
