### ISSUE TITLE
The new `dataloader_idx` argument not reflected in the doc string example of hook `transfer_batch_to_device`

### ISSUE THREAD

**Issue by lsqshr** [PyTorchLightning/pytorch-lightning#8845]
https://github.com/PyTorchLightning/pytorch-lightning/blob/cb2a8ed1b8f78386de4771d3bc59e19022e1b023/pytorch_lightning/core/hooks.py#L717

A new argument dataloader_idx has been added to the hook transfer_batch_to_device. However, it is not clear in the doc string example yet how it is going to be used.

**Comment by rohitgr7** [comment]
Mind send a PR with the correct update??

**Comment by lsqshr** [comment]
I would be happy to make an MR for sure. But to be honest, I do not know a scenario that `dataloader_idx` is needed here (this is why I checked the documentation for an example usage). Any idea?

**Comment by rohitgr7** [comment]
well, since lightning supports multiple dataloaders and there is no guarantee that the batch retrieved from each dataloader will have the same structure. For eg, in one DL it can be a simple torch tensor, and in another DL it can be a custom batch (using some custom class) that lightning can't handle explicitly. So in the first case, one can just use the pre-defined definition and in the second one, one can add some custom code in the same method itself. So dataloader_idx might come in handy and provide a little more flexibility here and that's why this feature was added. If not required, one can just simply ignore it.

**Comment by lsqshr** [comment]
thanks @rohitgr7 for the info. I will make an MR then.
