### ISSUE TITLE
Fix .test() on ddp

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning#885]
This might be broken on notebooks only.
#875 solves a few problems with .test()

However, ddp + .test might be broken on notebooks because of the "spawn" option. (likely #747).

**Comment by williamFalcon** [comment]
Anyone interested in looking at this?

**Comment by sneiman** [comment]
I am investigating this. Thats how I ran into the spawn issue with shared Q's. I am not using a notebook. This is (I believe) because ddp reduces tensors and parameters back to dev_ids[0] and there is no obvious way to get them back to the spawning CPU. I am slowly making progress, but don't have a lot of consistent time to put in.

**Comment by s-rog** [comment]
Isn't ddp broken in notebooks in the first place?
