### ISSUE TITLE
Add typing to the codebase

### ISSUE THREAD

**Issue by hadim** [PyTorchLightning/pytorch-lightning#887]
Python typing is a good way to rapidly check for coding issue while developing and it also allows to generate documentation with types automatically.

It's a good first issue for someone who wants to contribute to PL.

**Comment by awaelchli** [comment]
I like this and I'm happy to help out here. My suggestion is to do it gradually and split into multiple PRs, e.g., starting with Trainer and LightningModule, then Loggers and so on.

**Comment by Borda** [comment]
@awaelchli thx and happy to see more your PRs soon :]

**Comment by williamFalcon** [comment]
awesome! let's keep this going as we keep making fixes

**Comment by Borda** [comment]
It is not done yet lol

**Comment by awaelchli** [comment]
@hadim I am looking at adding more typing to the rest of the code base and I am facing this issue again with failing imports (e.g. in tests). I think it is related to forward referencing / cyclic references. 
For example, in the callbacks I need to import the Trainer and Lightning classes to type the callback signatures, which somehow fails at runtime. 
Have you faced such issues before?

**Comment by hadim** [comment]
No, I haven't but an easy fix is to use types as string. Instead of:

```python
class Node:
    def next() -> Node:
        pass
```

Try:

```python
class Node:
    def next() -> 'Node':
        pass
```

**Comment by luiscape** [comment]
This StackOverflow response adds more context to @hadim's response:

* https://stackoverflow.com/questions/33533148/how-do-i-specify-that-the-return-type-of-a-method-is-the-same-as-the-class-itsel

In short, that's an upcoming feature of Python 4.0. The most backward compatible workaround is the solution suggested by @hadim above.

**Comment by awaelchli** [comment]
Thanks for your suggestions. With just the string method there are no errors, but my IDE (pycharm) is complaining and suggesting that I still need to import Trainer (when I declare `trainer: 'Trainer'`). However, when I add [this](https://github.com/awaelchli/pytorch-lightning/blob/53dcd73162a1d4dd0dd196b20643da5a6490ef88/pytorch_lightning/callbacks/base.py#L10) import and run tests, it fails to import. 
The stackoverflow post doesn't say if the import is needed or not. Probably it does, otherwise how would the type system know which class it is?

**Comment by Borda** [comment]
Wow, is there road map for Python 4.0? What will be the last 3.x series? @luiscape

**Comment by Borda** [comment]
Wow, is there road map for Python 4.0? What will be the last 3.x series? @luiscape

**Comment by Borda** [comment]
I guess we can close it as we are continuously adding with every new PR...
