### ISSUE TITLE
Deprecate TrainerProperties Mixin and move property definitions directly into `trainer.py`

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#8946]
## 🚀 Feature

Deprecate the TrainerProperties: https://github.com/PyTorchLightning/pytorch-lightning/blob/938a191406fff5f51fba03fcf824f22d8d23c2e0/pytorch_lightning/trainer/properties.py

Move the properties directly to the trainer: https://github.com/PyTorchLightning/pytorch-lightning/blob/938a191406fff5f51fba03fcf824f22d8d23c2e0/pytorch_lightning/trainer/trainer.py#L104-L161

### Motivation

It's confusing to have trainer properties in multiple different classes. It would be more clear to have them all directly in trainer.py

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by ananthsub** [comment]
@daniellepintz maybe we could keep this issue specific to the properties, and file separate issues to discuss the other mixins. 

I agree with the push though; these mixins are historical artifacts of the prior trainer design. The mixins are not self-contained at all. 

It is very confusing having the properties listed separately, especially for what's on the public trainer API vs what's supposed to be private 

I know @awaelchli had similar thoughts in the past

**Comment by daniellepintz** [comment]
Sounds good, updated the description

**Comment by awaelchli** [comment]
This is only about moving the code from one file to the trainer.py right? And there is no deprecation necessary because we won't rename any attributes, right?

**Comment by awaelchli** [comment]
> It's confusing to have trainer properties in multiple different classes. It would be more clear to have them all directly in trainer.py

Just to give context of why things are the way they are:

The feedback for PL 1.0 was that the trainer is not easy to read for users. We wanted to make the trainer accessible so that users who start reading the code are guided to the right place from the very start (without needing to scroll hundreds of lines) and they can easily follow the code path. 

By merging all mixins into one, the trainer will now be cluttered again with a long list of properties, dataloading methods etc. where we will sacrifice readability and lose focus of what's important and what's not. 

To justify these changes, we can argue this is only a temporary state and we will invest efforts in making the trainer less a god class in the future.

**Comment by daniellepintz** [comment]
@awaelchli yes it is about moving the code. by deprecation I just meant deleting the TrainerProperties class and file.

thanks for the context! that makes sense. I am also wondering, do we really need all those properties? are they all used? Maybe we should try to reduce the number of properties.

If we can't remove any of the properties, maybe this issue isn't super hi-pri as there are pros and cons either way.

**Comment by ananthsub** [comment]
I'll also add, psychologically, we will be more incentivized to invest in efforts to make the trainer less of a god class if this is all in `trainer.py`. 

Because so much of the trainer logic is split across files like `properties.py`, the connectors, and the mixins, the problem is out-of-sight, out-of-mind. Stashing the code elsewhere is not a real solution and I'm looking forward to improving the current situation. I think it'll also force us to reckon with how complex the trainer has gotten, what do we absolutely have to live with, and what can we better organize. 

Given Lightning's claim to fame is that it's organized pytorch (not abstracted pytorch), it'll be critical that users and others in the community see this is true within the framework-internal codebase too!

**Comment by daniellepintz** [comment]
@ananthsub I completely agree! I add this task to my queue then.

**Comment by awaelchli** [comment]
> I am also wondering, do we really need all those properties? are they all used? Maybe we should try to reduce the number of properties.

We can try, but most of them are exposed for convenience access for users.

**Comment by tchaton** [comment]
Hey @awaelchli @carmocca, do you think we should do it. I am a bit perplex as i would prefer to come directly with an alternative instead of making an intermediate step there.

**Comment by carmocca** [comment]
I'd say this is very low priority. Additionally, when a "state/engine" interface is passed to the LightningModule to avoid the trainer reference, these properties could be part of it so they would naturally move there.

**Comment by ananthsub** [comment]
@carmocca @tchaton - this wouldn't be anything more than copy/paste the trainer property definitions into trainer.py and deleting the mixin. there's no other API changes that are part of this. it's simply to keep the trainer properties in one place to avoid extra hops when reading the code

**Comment by daniellepintz** [comment]
I can work on this if we decide to do it now. Agree it should be a simple PR

**Comment by daniellepintz** [comment]
Fixing this could also help avoid issues like #9427

**Comment by carmocca** [comment]
Since none of us have strong feelings against it, I think we can go forward with this.

I suggest you put all the properties at the end of the file as if you were concatenating the two files.

**Comment by awaelchli** [comment]
> Since none of us have strong feelings against it, I think we can go forward with this.

None of the team will have strong feelings about this because no Lightning engineer actually reads the `trainer.py` code anymore. We just navigate to where we need to be because we know where to go. But for users this is a different experience. The Trainer and LightningModule are the central objects of Lightning and people will attempt to read the code (and I wish I could encourage them!!). We used to have this somewhat readable structure: 

```
class Trainer:
   init
   fit  <- entry point, the interesting stuff!
   test  <- entry point, the interesting stuff!
   ...
   100's of useless lines of code making the trainer a god class
```

and now we have (and even more so after this PR):

```
class Trainer:
   init
   ...
   100's of useless lines of code nobody should read to understand Lightning
   ...
   fit <- entry point, the interesting stuff! (after PR at line 1124!!)
```

For this reason I suggest to put the properties at the bottom, even though I don't like this at all, maybe we can make a compromise?

**Comment by daniellepintz** [comment]
@awaelchli sure that's fine by me. I see other classes in Lightning don't follow a consistent style in terms of properties at top or bottom, so that sounds fine.

**Comment by awaelchli** [comment]
actually, in which classes did you see that? I believe we should fix that. Consistency is key.

**Comment by daniellepintz** [comment]
Some examples:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/base.py
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/accelerator.py

I agree we should fix it

**Comment by ananthsub** [comment]
> But for users this is a different experience. The Trainer and LightningModule are the central objects of Lightning and people will attempt to read the code (and I wish I could encourage them!!) and miserably fail. We used to have this somewhat readable structure:

I fully echo this. we have to make it as easy as possible for people to read & navigate the code. even in the examples @daniellepintz shared, we currently don't have a consistent style around how files are named. the base logger is in `loggers/base.py` ,  the base accelerator is in `accelerators/accelerator.py` - all of these minor discrepancies can add up when trying to navigate the codebase. this also came up here: https://github.com/PyTorchLightning/pytorch-lightning/pull/9414#discussion_r706770199

@awaelchli @tchaton - I think it would be very beneficial if we had a style guide written down, and which reviewers can enforce, to prevent these issues from occurring. we could then make it part of the [contributing doc](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md). What do you think?

**Comment by tchaton** [comment]
Having a style document to ensure future consistency on new addition definitely seem quite relevant today.

Personally, I am not a huge fan of properties being at the bottom, where the Trainer components will be several thousands of lines.  
But I don't have a good alternative to propose for this one.
