### ISSUE TITLE
after_save_checkpoint hook for generic Callback

### ISSUE THREAD

**Issue by favrei** [PyTorchLightning/pytorch-lightning#9202]
## 🚀 Feature

Create the after_save_checkpint hook for Callback in the same fashion as [the hook in the logger](https://github.com/PyTorchLightning/pytorch-lightning/blob/1c0786ebb80722f59b0115b0d28198b979b6c79d/pytorch_lightning/loggers/base.py#L75).

### Motivation

In our group, we will create a symlink whenever a better checkpoint is saved, so the automated scripts in the background can find the right checkpoint to start their job. Our in-house framework will handle the symlinks, but I find no entry point after we moved to Pytorch Lightning to implement the same feature.

### Pitch

A callback hook e.g., Callback.after_save_checkpoint so users can define their custom tasks whenever a better checkpoint is saved. For example:
```python3
class UpdateBestCheckpointCB(Callback):
    def after_save_checkpint(self, trainer, pl_module, **others):
        update_symlink_to_best(trainer)
```
### Alternatives

For now, we can always regard the latest checkpoint as the best, but it will be better if I can be sure about which is the best one.

**Comment by rohitgr7** [comment]
you can actually do
```
class CustomModelCheckpoint(ModelCheckpoint):
    def save_checkpoint(self, trainer):
        super().save_checkpoint(trainer)
        update_symlink_to_best(trainer)
```
although this seems a useful hook to have. Mind send a PR??

**Comment by favrei** [comment]
@rohitgr7 oh, this idea is great. Thanks for the advice.

**Comment by jinyoung-lim** [comment]
This issue seems to be open and unassigned. I'd love to take a stab at it as my first contribution!

**Comment by ananthsub** [comment]
I personally don't think the logger hook for after save checkpoint is good precedent for this either.

I like @rohitgr7 's earlier suggestion and would prefer making it easier to extend the `ModelCheckpoint` callback to enable  I'd personally prefer that over adding another checkpoint hook for these reasons: 

- Someone new could easily be confused as to what's the difference between `on_save_checkpoint` and `after_save_checkpoint` .
- the contract for `**others` is really loose. since `others` can be highly customized per use case, i'm not sure what entity would actually populate the `others` argument. The Trainer? The checkpoint callback? checkpoint callbacks for this.
- Moreover, `**others` doesnt give enough info to the callback writer around what it contains, so all the code to validate the kwargs is pushed to the hook implementor. 
- When does `after_save_checkpoint` actually run? After control returns from the model checkpoint callback entirely? At the end of the model checkpoint's `save_checkpoint` ? Whenever the trainer calls `save_checkpoint` ? After the IO plugin calls save_checkpoint ?  after each of these? https://github.com/PyTorchLightning/pytorch-lightning/blob/2e17b471f865ed76c940b027f19a50176a69af4b/pytorch_lightning/callbacks/model_checkpoint.py#L382-L389

**Comment by jinyoung-lim** [comment]
Good points @ananthsub! Below are my reply to your points with the limited knowledge that I have from trying to understand this feature request:
- _What would call `after_save_checkpoint`? Currently all callback hooks are run by the trainer._ : The hook is called by the trainer
- When does `after_save_checkpoint` actually run? After control returns from the model checkpoint callback entirely? At the end of the model checkpoint's `save_checkpoint` ? Whenever the trainer calls `save_checkpoint`? After the IO plugin calls `save_checkpoint` ? after each of these? : This was where I had the most trouble figuring out when trying to implement this feature (so I put out a draft for the PR in the hopes of discussing with other folks). My initial choice was to go for the mixture of at the end of the model checkpoint's `save_checkpoint` and whenever the trainer calls `save_checkpoint`, which, after reading your points and reading the code more I do not believe is not the expected behavior.
