### ISSUE TITLE
EarlyStopping: min_delta document description error

### ISSUE THREAD

**Issue by xyyimian** [PyTorchLightning/pytorch-lightning#9297]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/30361039/131928946-29e13a23-cea4-4006-a13c-d7d97fe05c20.png)

Actually, changes **equal** to min_delta will also do not qualify as an improvement.

According to the source code
![image](https://user-images.githubusercontent.com/30361039/131929231-bf22ebd0-f60e-40d4-b8f0-8e0044f5eba6.png)

![image](https://user-images.githubusercontent.com/30361039/131929078-12ba2579-5ed2-4f1b-beac-895baaf0bcfa.png)

Here, monitor_op is lt or gt, rather than lte or gte. Which means changes equal to min_delta won't qualify.

**Comment by awaelchli** [comment]
so I think we simply want to update the docs, right? 

For example, when `min_delta = 0` and let's say the metric stays exactly constant, we don't want to see that as an improvement: `0 = abs(current - base) >= min_delta = 0`. Otherwise we would never early-stop.
Hence, we want to keep comparison using strict relation operators. 

Is my reasoning ok?

**Comment by bamblebam** [comment]
@awaelchli I can do this if its ok.

**Comment by awaelchli** [comment]
sounds good, please go ahead and ping me for review or any questions you have. appreciated!
