### ISSUE TITLE
Remove ABC from Lightning Module

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#9499]
## Proposed refactoring or deprecation

No longer extend ABC in LightningModule:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L57

### Motivation

According to @carmocca in https://docs.google.com/document/d/1xHU7-iQSpp9KJTjI3As2EM0mfNHHr37WZYpDpwLkivA/edit?disco=AAAANOyYJFs this is legacy and can be removed. Originally added in https://github.com/PyTorchLightning/pytorch-lightning/pull/644 but we are no longer using the `@abstractmethod` decorator.

**Comment by PuneetDabral** [comment]
mam can i do?

**Comment by daniellepintz** [comment]
sure go for it!

**Comment by PuneetDabral** [comment]
mam i am new in open source also in github

**Comment by krkode** [comment]
hey @PuneetDabral , you can find this project's guide on how to contribute via their blog https://devblog.pytorchlightning.ai/quick-contribution-guide-86d977171b3a
(ps. im new to contributing as well so i tend to check a project's README.md file first because it typically has instructions on how to contribute)

**Comment by PuneetDabral** [comment]
@krkode hey bro can you please explain me in a simple language....
