### ISSUE TITLE
[RFC] Move some callbacks to Bolts

### ISSUE THREAD

**Issue by tchaton** [PyTorchLightning/pytorch-lightning#9506]
## Proposed refactoring or deprecation

Currently, Lightning provides several callbacks which aren't pure components:

* BackboneFinetuning: Optiniated way to perform backbone finetuning. This was meant to serve more like an example.

* ModelPruning: Relying on torch.prune API, this implements the `use_lottery_ticket_hypothesis` and scheduling logic for pruning. However, better solution out there exists and this callback is optionated. 

* StochasticWeightAveraging: Optiniatedv and hacky way of implementing SWA. Possibly contains some errors.

* QuantizationAwareTraining: Should this callback stays within Lightning, this is open to debate as it provides strong start for quantization.

The proposal would be to depreciate those callbacks from Lightning and move them to Lightning Bolts.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, finetuning and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

**Comment by tchaton** [comment]
@ananthsub @carmocca @awaelchli

**Comment by carmocca** [comment]
I don't see why we would do this. After all, these are not enabled by default and we are already removing the `Trainer` arguments for those who have one.

Is the argument to keep only those callbacks that impact the training flow or are just too important to the core functionality? e.g. `EarlyStopping`, `GradientAccumulationScheduler`, `ModelCheckpoint`, `ProgressBar`, `Timer`
All others are entirely self-contained (or should be!)

**Comment by Borda** [comment]
I would consider moving only experimental, nut none of the stable...
also once they have landed in PL it just confusing to move them somewhere else...
moreover, it would raise expectations on Bolts compatibility and production readiness if we move callbacks which are people already using and expecting to be high quality from PL

**Comment by tchaton** [comment]
I think Lightning should provide only pure engineering callbacks and not ML ones such as SWA, BackboneFinetuning, ModelPruning.

This is why I think they could be moved out.

**Comment by SeanNaren** [comment]
Thanks for making this issue @tchaton

I agree with @carmocca that we shouldn't consider moving out the current callbacks from this library. The fact that you mentioned SWA potentially contains errors is concerning and we should ask the authors/codeowners of the named callbacks to provide support.

However I do see an alternative point of view. For example if I made a PR to introduce the [SparseML Callback](https://lightning-bolts.readthedocs.io/en/latest/callbacks/sparseml.html) into Lightning, I could see a lot of friction, and a lot of unnecessary CI/reviewing to get this merged. In this scenario it makes sense to merge into Bolts where it's more contained and easier to make changes as its confined into a Callback (not touching any of Lightning's internals).

I think this is a great topic of conversation, but I think any further feature PRs should consider Bolts as a viable alternative if self-contained + the overhead of reviews/CI for Lightning is unnecessary for said feature. I think what I'd like to consider is adding Bolts as an optional extension for users to install to have these features available to them.

**Comment by Borda** [comment]
> I think Lightning should provide only pure engineering callbacks and not ML ones such as SWA, BackboneFinetuning, ModelPruning.

BackboneFinetuning is pure engineering callback

**Comment by ananthsub** [comment]
Thanks @tchaton for starting this discussion!

I think there are 2 facets to this:
1. What is our criteria for callbacks to be directly part of the Lightning? This means the Lightning team is responsible for supporting these implementations, handling feature requests, maintenance, etc. A rule of thumb could be: If we didn't have these callbacks today, would they be added now? I have vague recollections around including a `contrib` directory for callbacks - but such an offering can easily turn into an unmaintained dumping ground.

2. Do we recommend callbacks to handle model-related logic?

I think the callbacks offered by the framework, such as checkpointing, progress bars, early stopping are vital for people to easily get started. Obviously, the callbacks included by the Trainer by default must be part of the framework. But others, as ML engineering-focused ones, assume nothing of the LightningModule's internal structure. This fits the stated purpose of Callbacks in the docs to capture non-essential engineering code, while the LightningModule encapsulates the ML Research code.

However, the ones @tchaton has listed all assume something deeper about the model structure or training logic. I consider callbacks which mutate the LightningModule, or which create state that the model depends upon, to be anti-patterns. Callbacks for this purpose are also less natural to program with, as the logic is split between 2 entities. Users have to reason about the order of hook execution, loading of states, and mutations, all of which introduce areas for errors to enter.

Callbacks today are used for these purposes because they're the only mechanism we currently offer for code-sharing *across projects*. But here it seems like convenience of code sharing has taken precedence over correctness and our own design recommendations for organizing code *within a project* (see all the recent issues filed around SWA). 

IMO, this means we're missing some abstraction to more easily share this code which can be housed *inside of the LightningModule*.  This has always been an open question as now we're stretching beyond model interfaces and into implementations of LightningModules. Historically, users have been expected to fill this in because of how open-ended PyTorch naturally is. 

More recently, *frameworks building on top of Lightning* provide a more opinionated structure of the LightningModule, geared towards specific use cases. Hence I completely understand why Bolts, or Flash, could be more natural houses of these callbacks. Projects that include LightningModule implementations can have stronger opinions around the modeling design, which includes features like SWA, pruning, quantization, and fine-tuning.

I'll also relink my comment here around callbacks used for this fine-tuning: https://github.com/PyTorchLightning/pytorch-lightning/pull/8141#issuecomment-876015387
