### ISSUE TITLE
Improve LR Schedulers doc

### ISSUE THREAD

**Issue by grudloff** [PyTorchLightning/pytorch-lightning#9630]
## 📚 Documentation

The documentation on [configure_optimizer](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#configure-optimizers) seems to be confusing to newcomers, regarding the proper configuration of LR Schedulers through the use of the `lr_scheduling_config`. This leading to multiple issues that could be easily avoided, see #4929 #6948 #9475 #3869 #9300

In my particular case I was using OneCycleLR and unknowingly was doing steps on each epoch instead of on each step, see pytorch/pytorch#65417. As stated by @cowwoc this is an issue a lot of people stumble upon.

Even though the information is available on the documentation it may not be very user-friendly. The solution I incline for is adding an example as it is done for `ReduceLROnPlateau` but with the default configuration necessary for `OneCycleLR`.

**Comment by cowwoc** [comment]
Another approach is to detect suspicious configuration and issue a warning at runtime. Example: `Detected OneCycleLR using 'interval': 'epoch'. Are you sure you didn't mean 'interval': 'step'?`

Granted, this would only work for specific schedulers that we'd check for but for 95% of the users (who use off-the-shelf schedulers) this should go a long way towards catching mistakes.

Also, I suggest issuing a warning if an unknown configuration key is encountered. This would prevent (for example) users from mistakenly specifying a `interval` key at the same level as `lr_scheduler` instead of as a nested key.

**Comment by tchaton** [comment]
Dear @cowwoc,

This sounds like a great idea. Would you be willing to contribute this feature ?

Best,
T.C

**Comment by cowwoc** [comment]
Not at the moment, sorry.

**Comment by kingyiusuen** [comment]
I can help implement @cowwoc's idea if that's ok
