### ISSUE TITLE
ShardedDDP Warning

### ISSUE THREAD

**Issue by cutecows** [PyTorchLightning/pytorch-lightning#9643]
I'm getting the following warning after every validation:

warning root: sharded ddp detected that trainable params changed, because of eval/train mode or parameter freezing/unfreeze

Is this something I should worry about or can I just ignore it? Thanks!

**Comment by SeanNaren** [comment]
This shouldn't be an issue I think, however hopefully @blefaudeux might be able to provide more insight :)

**Comment by SeanNaren** [comment]
Any chance you could try fairscale master? I think I saw a few Sharded DDP fixes get merged.

**Comment by blefaudeux** [comment]
the warning can be legit, but it was a little too eager in the past, it has been fixed recently indeed ! Let me know if you still see any issues with a recent fairscale (the fix is in the latest pip release), should not be related to a spike in validation normally. Thanks for the heads up @SeanNaren !
