### ISSUE TITLE
`on_before_batch_transfer` fails when batch is unpacked.

### ISSUE THREAD

**Issue by ramonemiliani93** [PyTorchLightning/pytorch-lightning#9644]
## 🐛 Bug

I am trying to do some unpacking on the `on_before_batch_transfer` and even though it works for some batches, it fails at some point, it seems it fails when changing from training to validation. This is with the code on `master`. The same happens for `transfer_batch_to_device` and `on_after_batch_transfer`.

### To Reproduce

https://colab.research.google.com/drive/1Eu3a8lj0KUPTNbwj95uvJ0mwwYAfXzF6?usp=sharing

### Expected behavior

The training loop should run properly unpacking the batch before transfer.

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0+cu102
	- pytorch-lightning: 1.5.0dev
	- tqdm:              4.62.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

**Comment by rohitgr7** [comment]
this is happening in the last batch only.
the issue is here, data is moved to device when `store_on_device=False`.
not 100% sure if that is the correct fix since I am not familiar with this part of the codebase.. @tchaton wrote this logic.

https://github.com/PyTorchLightning/pytorch-lightning/blob/568a1e0a68fb8a2d8f2be7fae4f79c9068ca56fb/pytorch_lightning/utilities/fetching.py#L308-L309
