### ISSUE TITLE
Test every epoch why are you ignoring this feature????

### ISSUE THREAD

**Issue by ggaemo** [PyTorchLightning/pytorch-lightning#9662]
MANY issues are related to allowing "test every epoch" 
Why are you ignoring this feature????

**Comment by awaelchli** [comment]
Hello @ggaemo 
Can you point to some of the issues you saw and what you mean by "test every epoch"? 
A bit more information would be needed to start discussing a feature.

**Comment by ggaemo** [comment]
These are the previous issues that are closed without any support.

https://github.com/PyTorchLightning/pytorch-lightning/issues/5245

https://github.com/PyTorchLightning/pytorch-lightning/issues/9254

https://forums.pytorchlightning.ai/t/test-the-model-every-epoch/852

**Comment by rohitgr7** [comment]
doesn't `check_val_every_n_epoch` serves this purpose? testing is usually done at the end once you are sure that a model is good enough after you are done with cross-validation and stuff. Checking the performance of your model after some epochs is usually done on validation data because test data is unknown during model training in an ideal case. is there any reason why `check_val_every_n_epoch` isn't enough here?

**Comment by carmocca** [comment]
@ggaemo #9254 contains a discussion on why it was closed.

Please take a look. You can directly answer there to provide any arguments you think we missed.

I will close this issue as it is a duplicate and does not contribute to the conversation. Please, try to be respectful when opening an issue.
