### ISSUE TITLE
Deprecate `max_time` from the Trainer constructor

### ISSUE THREAD

**Issue by daniellepintz** [PyTorchLightning/pytorch-lightning#9824]
## Proposed refactoring or deprecation
Deprecate `max_time` from the Trainer constructor
https://github.com/PyTorchLightning/pytorch-lightning/blob/3392215ef69b483bff82bf7b0270c2349b33a73c/pytorch_lightning/trainer/trainer.py#L148

### Motivation

Same motivation as #9820 and #9500. 

We are trying to minimize the number of arguments on Trainer constructor: #9006
Right now we have two ways to configure a Timer, through the Trainer constructor argument `max_time`, and through the Timer callback. Let's make things simpler by only having one way, and keeping with the principle of putting customization logic into callbacks. This way we can also avoid having to check if the user set both places:
https://github.com/PyTorchLightning/pytorch-lightning/blob/3392215ef69b483bff82bf7b0270c2349b33a73c/pytorch_lightning/trainer/connectors/callback_connector.py#L215-L217

**Comment by carmocca** [comment]
Since `max_time` relates to the training flow, we consider it to be in the same category as `max_epochs`, `max_steps`, etc.

Since those are not going to be removed from the `Trainer`, it would be strange to force `max_time` to be passed as a callback.

This was discussed with the wider team so we are going to close this, feel welcome to continue the discussion.
