### ISSUE TITLE
error when using lr scheduler that TIMM provided

### ISSUE THREAD

**Issue by LuoXin-s** [PyTorchLightning/pytorch-lightning#9964]
## 🚀 Feature
**Use lr_scheduler more than torch provided.**
I notice that there are specific check codes to check that used lr_scheduler whether are torch naive, but this is kind of strange since use other lr_scheduler is normal.

### Motivation

I want to use lr_scheduler that timm provided, but got error as follows:
ValueError: The provided lr scheduler "<timm.scheduler.cosine_lr.CosineLRScheduler object at 0x7f876a168a60>" is invalid

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

<sub>

- [**Metrics**](https://github.com/PyTorchLightning/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Flash**](https://github.com/PyTorchLightning/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning

- [**Bolts**](https://github.com/PyTorchLightning/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch

- [**Lightning Transformers**](https://github.com/PyTorchLightning/lightning-transformers): Flexible interface for high performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

</sub>

cc @borda

**Comment by carmocca** [comment]
The error comes from this piece of code

https://github.com/PyTorchLightning/pytorch-lightning/blob/e5dfdf34f958d2eddccb205558763ae7aeedc0cc/pytorch_lightning/trainer/optimizers.py#L189-L192

Which checks that the optimizer subclasses `optim.lr_scheduler._LRScheduler`.
I believe we can relax this constraint.

@rwightman Is there a reason why your implementation does not subclass it?
Is it because it's marked as protected? There's an issue proposing making it public: https://github.com/pytorch/pytorch/issues/61232

**Comment by rwightman** [comment]
@carmocca I don't subclass because it's private, and also my interface is a bit different (but I think compatible where it overlaps). In general, not very pythonic to do a check like that (for subclass), as per duck typing, just call the methods. 

Overall I've never been particularly happy with the PyTorch schedulers although they are improving and finally getting features like warmup, etc. I tried to fix some of the bits I don't really like (statefulness, init, pre/post step or epoch consistency, especially), but still don't like aspects of my design. I'd like to revamp once again but have lots of other stuff ahead in the queue.

**Comment by LuoXin-s** [comment]
So what should I do so that I can get work on immediately? @carmocca @rwightman

**Comment by carmocca** [comment]
To workaround this check, you could define the following class:

```python
class MyCosineLRScheduler(CosineLRScheduler, _LRScheduler):
    ...
```

and use it in `configure_optimizers`. However, this will still fail later because the `timm` `scheduler.step` takes a positional `epoch` argument:

https://github.com/rwightman/pytorch-image-models/blob/02daf2ab943ce2c1646c4af65026114facf4eb22/timm/scheduler/scheduler.py#L67

which we do not provide:

https://github.com/PyTorchLightning/pytorch-lightning/blob/7b4df7bf919acfd7f7b39d780faeadb54aec9ade/pytorch_lightning/trainer/connectors/optimizer_connector.py#L86-L89


So for this to work, either the `timm` schedulers have to change or we need to explicitly add an integration for them.

**Comment by rwightman** [comment]
right, yeah, I require the epochs / steps as an arg since I didn't feel that state should be duplicated .... you'd have to write an adapter

**Comment by rohitgr7** [comment]
we do have optimizers wrapped around optimizers that are not subclassed with `optim.Optimizer`
https://github.com/NVIDIA/apex/blob/master/apex/fp16_utils/fp16_optimizer.py
https://github.com/microsoft/DeepSpeed/blob/1fc74cb9c81668b5ff0046446f8004d4cf8dc2d5/deepspeed/runtime/zero/stage3.py#L595

possibly we can remove this check and let users configure their scheduler step as well just like `LightningModule.optimizer_step`? this way we can support timm schedulers.
